### ISSUE TITLE
`prefixCls` is not inherited in some components

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#10855]
This is an umbrella issue to track the problem of `prefixCls`. 

- [ ] #10017 Tag: prefixCls not passed to Icon
- [ ] #10565 Modal: prefixCls not passed to Button
- [x] #12546 Modal.xxx: prefixCls not passed to mask
- [ ] #10042 Upload - Dragger: Pass prefixCls to UploadList - Upload
- [ ] Transfer
- [ ] #12676 Popconfirm: prefixCls not passed to Button

**Comment by yesmeck** [comment]
@chungwong Not the same issue.

**Comment by yesmeck** [comment]
From internal discussions:

We'll introduce a new provider called `ConfigProvider` for the configuration of `prefixCls`.

```javascript
import { ConfigProvider, Button } from 'antd';

<ConfigProvider prefixCls="awesome-">
  <Button>A Button</Button>
</ConfigProvider
```

produces:

```javascript
<button type="button" class="awesome-btn"><span>A Button</span></button>
```

**Comment by afc163** [comment]
It is resolved via #12991

**Comment by coolcorexix** [comment]
I had this problem but it is very inconsistent between development and production. In local, the prefix get inherited properly

![image](https://github.com/user-attachments/assets/e9a8c78e-097d-4354-8ee0-49f80fab6aa6)

but on stage, it keep using antd prefix

![image](https://github.com/user-attachments/assets/4056efbd-9dde-40e8-818f-325a6e030617)


I did wrap all these children inside a ConfigProvider, the children code is as follow

```
 return (
    <Navbar
      isCollapsed={navBarCollapsed}
      onCollapse={onNavBarCollapsClicked}
      isDisplayBackButton={isDisplayBackButton}
    >
      {sideHeaderSection}
      {/* This is the inspected element */}
      <Menu
        selectedKeys={[activeKey]}
        onClick={onSelectMenu}
        style={{
          borderColor: 'transparent',
          backgroundColor: '#f4f7fa',
        }}
        mode='inline'
      >
        {backSection}
      </Menu>
      {listSection}
    </Navbar>
  );
```
