### ISSUE TITLE
Document Translation

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#1471]
We just finished most of translate jobs and published at [beta.ant.design](http://beta.ant.design), welcome to visit it and review the translation. Give us PR if you find any typos. 🎅 

---

## Volunteer Wanted

Hey, guys! We are going to provide English documentation. 

But we are short of staff :-( So, we want some volunteers to help us to translate antd's documentation into English. Every translation task needs a translator and a reviewer. Both of them are expected that they had used the component(`Affix` `Alert` etc...) in real world.

### Translator

A translator should be familiar with both Chinese and English. 

If you want to be a volunteer translator, just comment this issue. For example, "I want to be the translator of button and alert ....". And then, we will update this issue(e.g. button (translator: @benjycui, reviewer:  @waywardmonkeys )), and ping you. 

Contributing:

1. Fork [ant-design](https://github.com/ant-design/ant-design) and `git clone`
1. Create a branch starting at `master` and name it as `translation-button`
1. `npm install && npm start`, see: [Development](https://github.com/ant-design/ant-design/wiki/Development)
1. Find Markdown files under `components/xxx`(xxx is the component which you need to translate), `index.md` and `demo/*.md` use different format, see: https://github.com/ant-design/ant-design/issues/1423
1. Just translate it, and you had better read our [advice](https://github.com/ant-design/ant-design/issues/1471#issuecomment-213636139) first.
1. Create a pull request to `ant-design:master` when your translation is done, and ping your reviewer.
1. PR will be merged, if your reviewer think it is OK.

See: 
* https://github.com/ant-design/ant-design/tree/master/components/button
* https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md

### Reviewer

A reviewer should be a native English speaker.

If you want to be a volunteer reviewer, just comment this issue. For example, "I want to be the reviewer of button and alert...". And then, we will update this issue(e.g. button (translator: @benjycui, reviewer:  @waywardmonkeys )), and ping you. 

After your corresponding translator finish his/her work, you should review and provide some advice.

Example: #1932

### TODOs

/docs/react
  * [x] getting-started.md (translator: @benjycui, reviewer: )
  * [x] introduce.md (translator: @benjycui, reviewer: )
  * [x] install.md(had been translated into English, but it's outdated). (translator: @benjycui, reviewer: )

> * CHANGELOG.md and upgrade-notes.md won't be translated, but we will provide English edition while releasing next version.

/components
  * [x] affix (translator: @afc163 , reviewer: )
  * [x] alert (translator: @afc163 , reviewer: ) 
  * [x] badge (translator: @afc163 , reviewer: )
  * [x] backtop (translator: @ddcat1115 , reviewer: )
  * [x] breadcrumb (translator: @forthedamn , reviewer: )
  * [x] button (translator: @benjycui, reviewer:  @waywardmonkeys )
  * [x] calendar (translator: @forthedamn, reviewer: )
  * [x] card (translator: @superRaytin, reviewer: )
  * [x] carousel (translator: @superRaytin, reviewer: )
  * [x] cascader (translator: @superRaytin, reviewer: )
  * [x] checkbox (translator: @benjycui, reviewer: )
  * [x] collapse (translator: @ddcat1115, reviewer: )
  * [x] date-picker (translator: @ddcat1115, reviewer: )
  * [x] dropdown (translator: @ddcat1115, reviewer: )
  * [x] form (translator: @GrayChoi, reviewer: )
  * [x] icon (translator: @ryangun, reviewer: )
  * [x] input (translator: @visvadw, reviewer: )
  * [x] input-number (translator: @ryangun, reviewer: @visvadw)
  * [x] layout (translator: @forthedamn , reviewer: )
  * [x] locale-provider (translator: @ddcat1115, reviewer: )
  * [x] menu (translator: @wenshiqi0: reviewer: )
  * [x] message (translator: @u9lyfish, reviewer: )
  * [x] modal (translator: @GrayChoi, reviewer: )
  * [x] notification (translator: @GrayChoi, reviewer: )
  * [x] pagination (translator: @ddcat1115, reviewer: )
  * [x] popconfirm (translator: @wenshiqi0: reviewer: )
  * [x] popover (translator: @wenshiqi0: reviewer: )
  * [x] progress (translator: @ddcat1115, reviewer: )
  * <del>queue-anim</del> will be moved to [Ant Motion](http://motion.ant.design/)
  * [x] radio (translator: @qiuyuntao, reviewer: )
  * [x] rate (translator: @qiuyuntao, reviewer: )
  * [x] select (translator: @RaoHai , reviewer: )
  * [x] slider (translator: @RaoHai , reviewer: )
  * [x] spin (translator: @RaoHai , reviewer: )
  * [x] steps (translator: @ddcat1115 , reviewer: )
  * [x] switch (translator: @ddcat1115 , reviewer: )
  * [x] table (translator: @afc163 , reviewer: @manV)
  * [x] tabs (translator: @xueqingxiao, reviewer: )
  * [x] tag (translator: @xueqingxiao, reviewer: )
  * [x] time-picker (translator: @liqi07, reviewer: )
  * [x] timeline (translator: @liqi07, reviewer: )
  * [x] tooltip (translator: @liqi07, reviewer: )
  * [x] transfer (translator: @liqi07, reviewer: )
  * [x] tree (translator: @GrayChoi, reviewer: )
  * [x] tree-select (translator: @ddcat1115 , reviewer: )
  * [x] upload (translator: @hellowenqi , reviewer: )
  * [x] ~~validation~~

/docs/spec
  - [x] Design docs PR (translated at intenal by designer) @benjycui 

- [x] Home Page and Footer

- [ ] https://github.com/ant-design/ant-design/blob/master/docs/resource @xueqingxiao 
- [x] https://github.com/ant-design/ant-design/tree/master/docs/practice @visvadw

**Comment by afc163** [comment]
`install.md` should be updated.

**Comment by benjycui** [comment]
## Glossary

// working on it

**Comment by plandem** [comment]
i can help with russian :) not english native :(

**Comment by manV** [comment]
I can help reviewing table

**Comment by benjycui** [comment]
@manV updated and thanks! 

You can review more translation tasks, if you have time :-)

**Comment by benjycui** [comment]
@plandem `antd` only provide Chinese and English documentation, sorry and thanks.

**Comment by manV** [comment]
@benjycui sure I can help reviewing other translations as well, please mention me whenever you need :+1:

**Comment by afc163** [comment]
Affix, Alert, Badge. I will translate these component.

**Comment by RaoHai** [comment]
Select, Slider, Spin.

**Comment by qiuyuntao** [comment]
rate, radio

**Comment by benjycui** [comment]
@afc163 @RaoHai @qiuyuntao updated and thanks!

**Comment by afc163** [comment]
去 http://echojs.com/  上发一个引关注。

**Comment by forthedamn** [comment]
calendar

**Comment by benjycui** [comment]
@forthedamn updated and thanks!

**Comment by superRaytin** [comment]
Card, Carousel, Cascader, Checkbox

**Comment by benjycui** [comment]
@superRaytin updated and thanks!

**Comment by razagill** [comment]
This is great work guys! I can help review the translations wherever you need, so just mention me in the issue where you see fit.

**Comment by ddcat1115** [comment]
date-picker
dropdown

**Comment by benjycui** [comment]
@ddcat1115 updated and thanks!

**Comment by forthedamn** [comment]
breadcrumb

**Comment by afc163** [comment]
各位翻译的时候尽量不要从中文直译，按语义重新组织语言。

**Comment by benjycui** [comment]
@forthedamn updated and thanks!

**Comment by u9lyfish** [comment]
message

**Comment by benjycui** [comment]
@u9lyfish updated and thanks!

**Comment by u9lyfish** [comment]
@benjycui demo 代码中的中文如何处理？是直接替换为英文翻译，还是也分为两份代码？

How should I deal with Chinese texts within code snippets in /demo? Should I replace them with English versions, or split the code snippet into two?

**Comment by benjycui** [comment]
共享一份代码，代码中的中文改为英文，see：https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md

@u9lyfish

**Comment by forthedamn** [comment]
col

**Comment by afc163** [comment]
@forthedamn Layout is Assigned to u (col and row included)

**Comment by ddcat1115** [comment]
backtop & collapse , already marked

**Comment by liqi07** [comment]
timeline

**Comment by ddcat1115** [comment]
@liqi07  thanks and updated : )

**Comment by xueqingxiao** [comment]
tabs, tag

**Comment by benjycui** [comment]
@xueqingxiao updated and thanks!

**Comment by xueqingxiao** [comment]
@benjycui NP. I think, we'd better rename 'index.md' to 'README.md'.

**Comment by benjycui** [comment]
> rename 'index.md' to 'README.md'.

After we provide english documentation, `index.md` will be split into `index.zh-CN.md` and `index.en-US.md`.

So rename them into `README.zh-CN.md` && `README.en-US.md` is meanless.....

**Comment by GrayChoi** [comment]
I can help with translating tree component.

**Comment by benjycui** [comment]
@GrayChoi update and thanks.

**Comment by afc163** [comment]
- [ ] Design docs PR (translated at intenal by designer) @benjycui

**Comment by ryangun** [comment]
I want to be the translator of icon, input and input-number.

**Comment by benjycui** [comment]
@ryangun thanks and updated!

**Comment by ryangun** [comment]
@benjycui Oh...Where are the Chinese documentations of input?

**Comment by benjycui** [comment]
> Find Markdown files under components/xxx(xxx is the component which you need to translate), index.md and demo/*.md use different format, see: #1423

@ryangun please read the first comment of this issue: https://github.com/ant-design/ant-design/issues/1471#issue-149981757

**Comment by ryangun** [comment]
@benjycui I delete the repository and fork again, then all is ok.

**Comment by wenshiqi0** [comment]
I'll take menu, popconfirm and popover

**Comment by benjycui** [comment]
@wenshiqi0 updated and thanks!

**Comment by GrayChoi** [comment]
I can help with translating form, modal, notification.

**Comment by benjycui** [comment]
@GrayChoi updated and thanks!

I am a bad guy. 😅

**Comment by liqi07** [comment]
time-picker
tooltip
transfer

**Comment by afc163** [comment]
@liqi07 :+1:

**Comment by hellowenqi** [comment]
I want to be the translator of upload

**Comment by benjycui** [comment]
@hellowenqi updated and thanks!

**Comment by hellowenqi** [comment]
## Two errors occur after running 'npm install && npm run ' on windows platform

### 1.  cannot load path properly.  I solved this problem by editing path directly in file `bisheng`
![image](https://cloud.githubusercontent.com/assets/10651504/17238816/9c712a9e-5591-11e6-977c-30946125048c.png)

### 2. the second problem is it cannot load file data.js which is empty. Is it a problem of `bisheng` or a problem of dora ?

**Comment by benjycui** [comment]
@hellowenqi trace https://github.com/benjycui/bisheng/issues/26

**Comment by visvadw** [comment]
This is a wonderful design and implementation 👍  and I want to contribute.
Let me first start with the translation and review of `tree-select`.

I have noticed that the translation is assigned to @ddcat1115  (`tree-select (translator: @ddcat1115 , reviewer: )`), but he did not start yet.

Besides this, I can do the review of other components, so I will let you pick up something. 😃

**Comment by benjycui** [comment]
@visvadw you can review those translations in `master` now, and you can create a PR if you want to improve any of them.

**Comment by ddcat1115** [comment]
@visvadw  You can review the `TreeSelect` now 😸 

#2582

**Comment by afc163** [comment]
I am translating Table now.

**Comment by visvadw** [comment]
I want to review the translation of `Input` and `InputNumber`. 
Please include me in the first message of this issue as it helps me keeping track of what to do.
For now, as I remember 😄, I reviewed completed or partially the Form, TreeSelect, and Transfer.

**Comment by benjycui** [comment]
@visvadw updated and thanks!

**Comment by oeddyo** [comment]
Hi there, I can help reviewing some of the docs. Kindly let me know priorities

**Comment by benjycui** [comment]
@oeddyo https://github.com/ant-design/ant-design/issues/1471#issuecomment-236472039

We are going to finish all the translation tasks before 20th Aug. So there is no priorities now. And you can review the master which we had translated, the directory structure refer: https://github.com/ant-design/ant-design/issues/1471#issue-149981757

Thanks!

**Comment by afc163** [comment]
- [ ] Home Page and Footer

**Comment by jillyan** [comment]
Hello, I want to be the translator of button and alert. I am a developer in a foreign company, we decide to use react this year. we have daily meeting with foreign colleagues. Though my English is not that good, but I'd like to commit contribution.

**Comment by benjycui** [comment]
@jillyan `Button` and `Alert` had been translated. But, you can review any docs if it had been translated and create a PR if you have any idea to improve those docs.

**Comment by visvadw** [comment]
@ryangun Did you finish any translation (of Icon, Input or InputNumber)?

**Comment by ryangun** [comment]
@visvadw I'm sorry about that. I haven't even started the translation of Input yet, so you can just do it, thank you for your help!

**Comment by oeddyo** [comment]
I can review more now.

Kindly let me know what's on going :)

**Comment by benjycui** [comment]
@xueqingxiao @hellowenqi if you have no time, I am going to finish your tasks, OK?

**Comment by hellowenqi** [comment]
I`m sorry I have not finished the task yet. I can finish the task in two days. @benjycui

**Comment by xueqingxiao** [comment]
@benjycui in progress.

**Comment by benjycui** [comment]
It seems that the following tasks haven't been translated...

* input
* tag 
* Home Page and Footer

**Comment by xueqingxiao** [comment]
@benjycui I will finish tag in this weekend.

**Comment by visvadw** [comment]
@benjycui `Input` is my todo for tomorrow.

**Comment by visvadw** [comment]
@benjycui I am done with the translation of `Input` component. See [PR 2789](https://github.com/ant-design/ant-design/pull/2789).

**Comment by visvadw** [comment]
For the next 10 days I will be on vacation and the access to email/Internet may be limited.

**Comment by visvadw** [comment]
It looks like that the Internet access is pretty good. Therefore, I could do other reviews, if needed.

**Comment by kvetoslavnovak** [comment]
Well done. Is there any plan for release date?

**Comment by nie-xin** [comment]
It seems all done except some reviews. Could we have a beta doc version at this time and complet the review later? I can't wait to introduce antd to my teammates!

**Comment by kvetoslavnovak** [comment]
I agree. To have it uploaded, even as a beta, may bring faster and better feedback of reviews.

**Comment by afc163** [comment]
Maybe a `beta.ant.design`?

**Comment by afc163** [comment]
- [ ] not finished：https://github.com/ant-design/ant-design/blob/master/docs/resource/download.en-US.md

**Comment by xueqingxiao** [comment]
@afc163 I can help to translate resource.

**Comment by visvadw** [comment]
@afc163 I will translate and review docs/practice.

**Comment by benjycui** [comment]
@xueqingxiao @visvadw updated and thanks!

**Comment by benjycui** [comment]
@nie-xin @kvetoslavnovak antd@2.0.0-beta and it's [documentation](http://beta.ant.design/) are published.

If anyone want to improve those documentation, just click the following button and edit on GitHub:

![image](https://cloud.githubusercontent.com/assets/3580607/18380209/dd995072-76a8-11e6-888e-3c8525fd0f09.png)

**Comment by nie-xin** [comment]
@benjycui Great! I will help as much as I can!

**Comment by xueqingxiao** [comment]
@benjycui Great! But the API doc seems still Chinese simplified.

**Comment by benjycui** [comment]
> But the API doc seems still Chinese simplified.

It should be Ok now... My bad.

**Comment by visvadw** [comment]
[PR 2998](https://github.com/ant-design/ant-design/pull/2998) is the translation (and review) of docs/practice section. I hope it is accurate.

**Comment by kvetoslavnovak** [comment]
Generally looks fine to me.
Some isue 

**Not Translated pages**
- http://beta.ant.design/changelog - heading translation should be enough
http://beta.ant.design/docs/react/upgrade-notes - - heading translation should be enough

**Not Translated Compnents**
http://beta.ant.design/components/mention/
**Localisation**
- there are components ( Pagination, DatePicker, TimePicker, Calendar, Popconfirm, Table, Modal, Button, Select, Transfer, Radio) which should use LocalProvider en_US to render according to http://beta.ant.design/components/locale-provider/ 

**In Code Text**
-  code examples still contain some Chinese texts:
- http://beta.ant.design/components/button/ - Icon example
- http://beta.ant.design/components/checkbox/ - Check all example
- http://beta.ant.design/components/cascader/ - all cascading texts
- http://beta.ant.design/components/input/ - Basic usage example - placeholder text
- http://beta.ant.design/components/radio/ - Radio style and Radio size  examples
- http://beta.ant.design/components/select/ - Automatic completion and Coordinate examples
- http://beta.ant.design/components/slider/ -Graduated slider example
- http://beta.ant.design/components/upload/ - Uploading by clicking example
- http://beta.ant.design/components/alert/ - Icon example
- http://beta.ant.design/components/badge/ - Dynamic example
- http://beta.ant.design/components/dropdown/ - all examples
- http://beta.ant.design/components/modal/ - Basic example
- http://beta.ant.design/components/popconfirm/ - Basic, Placement, Conditional trigger examples
- http://beta.ant.design/components/popover/ - all examples
- http://beta.ant.design/components/progress/ - Custom text format example
- http://beta.ant.design/components/table/ - dataSource in all examples
- http://beta.ant.design/components/timeline/ - all examples
- http://beta.ant.design/components/tooltip/ - Tooltip button example
- http://beta.ant.design/components/menu/ - all examples
- http://beta.ant.design/components/steps/ - all examples
- http://beta.ant.design/components/tabs/ - Position example
- http://beta.ant.design/components/back-top/ - all examples
- http://beta.ant.design/components/spin/ - Embedded mode and Customize description examples

**Comment by kvetoslavnovak** [comment]
Should I propose each translation edit as PR?

**Comment by visvadw** [comment]
@kvetoslavnovak Comments should be here, as this is the main thread of discussion about translation topic. Yes, each translation can be part of a PR, it this works for you.

@afc163 I've noticed that although (at least some of the) demos contains Chinese content, the source it is all English. Example: [Button icon demo](http://beta.ant.design/components/button/) and [its source](https://github.com/ant-design/ant-design/blob/master/components/button/demo/icon.md).

**Comment by kvetoslavnovak** [comment]
@visvadw @afc163 this buttun icon example source was corrected just few hours ago because of my PR https://github.com/ant-design/ant-design/pull/3000 so this is there is no confusion

**Comment by visvadw** [comment]
@kvetoslavnovak Now that some of the items from the list has been translated or they are about to be (PRs are open), so the list needs to be updated.

**Comment by kvetoslavnovak** [comment]
I will try to keep the list updated.

**Comment by benjycui** [comment]
@visvadw @kvetoslavnovak PRs were merged and beta.ant.design was updated.

**Comment by wuyahuang** [comment]
I'm a front-end engineer. I want to be the translator of any untranslated components.

**Comment by johnsky123** [comment]
D:\antdemo\blog>atool-build
module.js:327
    throw err;
    ^

Error: Cannot find module 'atool-build/lib/webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\antdemo\blog\webpack.config.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
can you tell me what's the reason of this? and can i solve it?

**Comment by xueqingxiao** [comment]
@benjycui @afc163 is there anyone trying to translate [pattern](http://beta.ant.design/docs/pattern/navigation)?

**Comment by benjycui** [comment]
Pattern will be updated in this month, so it's meaningless to translate it right now.

Change log and upgrade guide are useless for foreigners for most of them are new comers(OK, some had use antd for a long time..). And we will provide English change log in next version.

**Comment by afc163** [comment]
Change log and upgrade guide should translate heading.

**Comment by visvadw** [comment]
Yes, please! The english versions of Change Log and Upgrade Guide are helping everybody.
Even new comers may benefit from reading it as it may provide some guidance of what is evolving.

**Comment by kvetoslavnovak** [comment]
I have updated the issues list.

**Comment by benjycui** [comment]
@kvetoslavnovak thanks!

**Comment by kvetoslavnovak** [comment]
I have proposed translation PR for Menu and (partially) Mention.

**Comment by kvetoslavnovak** [comment]
@benjycui thanks for merging my last commits for Menu and Mention translation. 
But I cannot see updated http://beta.ant.design/components/menu/ and http://beta.ant.design/components/mention/ 
???

**Comment by benjycui** [comment]
I forgot to publish. It should be OK now.

**Comment by kvetoslavnovak** [comment]
Here is updated (cleared) list of residual issues:

**Localisation**
-  [ ]  there are components ( Pagination, DatePicker, TimePicker, Calendar, Popconfirm, Table, Modal, Button, Select, Transfer, Radio) which should use LocalProvider en_US to render according to http://beta.ant.design/components/locale-provider/ 

**In Code Text**
-  [ ]  http://beta.ant.design/components/dropdown/ - all examples
- [ ]  http://beta.ant.design/components/mention/ - Controlled example
-  [ ]  http://beta.ant.design/components/modal/ - Basic, Asynchronously close, Confirmation modal dialog, Manual to destroy and To customize the position of modal
 examples
-  [ ]  http://beta.ant.design/components/popconfirm/ - Basic, Placement, Conditional trigger examples
-  [ ]  http://beta.ant.design/components/popover/ - all examples
-  [ ]  http://beta.ant.design/components/table/ - data in all examples
-  [ ]  http://beta.ant.design/components/timeline/ - all examples
-  [ ]  http://beta.ant.design/components/steps/ - all examples

**Comment by afc163** [comment]
@kvetoslavnovak You can open another issue for demo translation. We close this now.

**Comment by kvetoslavnovak** [comment]
Congratulation to 2.0.
@afc163  OK, I will open the ussue so we can keep track regarding residual translation issues.

**Comment by kvetoslavnovak** [comment]
The residual issues are here #3200

**Comment by benjycui** [comment]
After `antd-mobile@1.0` is published, it means that `antd-mobile` is stable enough, and we want to translate its documentation into English now.

If someone is interested in this, you can trace: https://github.com/ant-design/ant-design-mobile/issues/329

**Comment by benjycui** [comment]
Could someone help us to translate intl-example? https://github.com/ant-design/intl-example/issues/13

**Comment by abenhamdine** [comment]
I noticed many parts are still untranslated in docs, : 
- in Guidlines, starting from Fonts : https://ant.design/docs/spec/introduce
- the whole Patterns section : https://ant.design/docs/pattern/navigation

I don't speak chinese, and use Google Translate for this seems very tedious.
If someone could provide a least a succint english translation, I could polish the result.

**Comment by loganpowell** [comment]
I do not speak Chinese, but have found Chrome's native translation feature (in the context menu: right-click) gets me 90% there. I would be happy to use this and polish the text to make it easier to understand. Let me know if this would be helpful.

**Comment by benjycui** [comment]
@loganpowell just PR to us when you found any issue in our document.

**Comment by acomito** [comment]
Do we know how much text needs translating between antd and antd mobile (maybe a guess at word count)? I would be willing to fund/crowdfund hiring a translator via a freelance site (upwork, etc).

**Comment by choudlet** [comment]
I can help with translating and don't see any open issues now. I would be happy to start translating https://ant.design/docs/pattern/navigation since it's still in Chinese! Please let me know if this is the best thread to contribute on and how I should help.

**Comment by shenlin192** [comment]
I want to be the translator of:

- [Layout](https://ant.design/docs/spec/layout) in Guidelines. 
- [form](https://ant.design/docs/pattern/form) in Patterns.

I'm familiar with both Chinese and English and I'm a fan of antd. 
It would be a pleasure for me to help.

**Comment by afc163** [comment]
Thank you guys! @shenlin192 @choudlet

**Comment by afc163** [comment]
Trace for the rest untranslated documents at https://github.com/ant-design/ant-design/issues/6931

**Comment by tsaiDavid** [comment]
I wanted to point out that I'd love to help with any translating or proofreading - if anyone can point me in the right direction, I'm certain I can provide some added clarity and polish to the final text.

**Comment by benjycui** [comment]
@tsaiDavid I am not sure if you had noticed these edit button, actually, you can polish our documentation any time, feel free to PR, thanks!

![image](https://user-images.githubusercontent.com/3580607/32998865-2d6ee8ec-cd64-11e7-90ce-693c9a94b247.png)

![image](https://user-images.githubusercontent.com/3580607/32998874-39b59eca-cd64-11e7-96d4-c8c51825bd8b.png)

**Comment by richardzyx** [comment]
Hi all, I would love to volunteer for the translation work, but couldn't find a good task list with references to what's been done + what are the priorities. #6931 is tagged inactive as well. We are using Ant Design in one of our projects as a pilot, so I would want to see the design language docs fully translated.

Right now here are the ones with only Chinese docs:
- Visual/Layout
- Visual/Font
- Patterns/Overview
- Patterns/Copywriting
- Patterns/Data Entry
- Patterns/Data Display
- Patterns/Feedback
- Visualization
- Motion

How can the open source community help with the spec translation effort? Thanks! =]

**Comment by yesmeck** [comment]
@richardzyx I've updated #6931, leave a comment on that issue if you are going to translate one of the docs, I will update the list.

**Comment by badaljain** [comment]
Hi Tam,

I was just wondering as Ant design itself provides "Internationalization" feature but most of the website is not even translated. its'nt it irony?

**Comment by afc163** [comment]
@badaljain Welcome to help us.

**Comment by kirkins** [comment]
Hi is this issue closed?

I'm trying to read this page https://ant.design/docs/spec/data-entry

Thanks anyone who can help :-)

**Comment by shenlin192** [comment]
Hello @kirkins @afc163, 

I can help translating https://ant.design/docs/spec/data-entry this page.

**Comment by shenlin192** [comment]
It seems that this issue is closed

**Comment by dengfuping** [comment]
@shenlin192 You could leave a comment about which docs you want to translate on issue #6931 and we will update that list.

**Comment by michellechsy** [comment]
Hi,
Is anyone working on the translation for 'Data Entry' or 'Data Display' now? If no, I can help on either one (e.g. 'Data Entry' first) :) please let me know if still need. Thanks

**Comment by afc163** [comment]
@michellechsy We still need your help~

**Comment by michellechsy** [comment]
@afc163 alright~ I will work on 'Data Entry' then :)

**Comment by dchan3** [comment]
I apologize if I am a little late on this issue, but I can help with translating Copywriting. When I read the original Chinese document, I found it seems to consist of many examples specific to the Chinese language, so I will see if I can provide more general examples that apply to other languages.

**Comment by afc163** [comment]
@dchan3 Sure, just try it.

**Comment by lirenyeo** [comment]
I can help translating [Dark Theme](https://ant.design/docs/spec/dark) if needed.

**Comment by yoyo837** [comment]
@lirenyeo Yes, PR welcome!

**Comment by yatinglu1993** [comment]
I can help with the Visualization Page and Detail Page, if it's still needed. :)

**Comment by OpsLingyu** [comment]
I can help with translating the Table and Complex Table for 2.13.11., my company is currently using it so I assume it's still vastly in use. Let me know if that's needed.
