### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1538]
- [x] rewrite in TypeScript #1846
- [x] Internationalization Documentation #1471 :us:
- [x] Component AutoComplete #1100
- [x] Component Mention #1410
- [x] New Icon
- [x] Table multiple header #1430
- [x] Cascader Search #1944
- [x] FormItem vertical layout #2449
- [x] Use [moment](http://momentjs.com/) in Date Components https://github.com/ant-design/ant-design/issues/2717
- [x] `getFieldProps` takes over all the properties of a form control https://github.com/ant-design/ant-design/issues/1533
- [x] remove deprecated code and relative warning
- [x] upgrade rc-menu to 5.x
- [x] Remove Table `columnsPageSize` & `columnsPageRange` #2883
- [x] Upgrade all deps: https://david-dm.org/ant-design/ant-design
- ...

The following features are going to be implemented in 2.x, see: https://github.com/ant-design/ant-design/projects/2

- [ ] Component Editor #1083 
- [ ] ant-design-icons #1473 
- [ ] New Color system ❓ 
- [ ] RangePicker Preset Links #1418
- [ ] Left direction popup for Menu, Cascader and etc. #1150

**Comment by plandem** [comment]
i would like to see something like this:
https://github.com/STRML/react-grid-layout

**Comment by ChenLi0830** [comment]
New Color system +1

**Comment by kvetoslavnovak** [comment]
All suggested topics are great.

**Comment by iwege** [comment]
fixed table  maybe can look at https://github.com/facebook/fixed-data-table

**Comment by kvetoslavnovak** [comment]
Could you also add uxcore-tinymce https://github.com/uxcore/uxcore-tinymce`?
I think you could just pick up the one from UXCore http://uxco.re/components/tinymce/ as there is little to no need for any different styling.

**Comment by afc163** [comment]
updated at 2016-07-05T03:01:25.832Z

**Comment by afc163** [comment]
- [ ] Upgrade all deps: https://david-dm.org/ant-design/ant-design

**Comment by benjycui** [comment]
Unfinished features will be implemented in 2.x, see: https://github.com/ant-design/ant-design/projects/2

If anyone wants to create PR for any feature, just comment in that issue. Thanks 😄 

And this issue close now.
