### ISSUE TITLE
Menu has lot of problems in 3.15 & 3.16

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15801]
- [x] Menu 导航菜单 收缩时,首次hover出现闪现,点击后只出现一半图标 #15800 
- [x] inline Menu inside Layout Sider still flash and shake when collapsed #15797 
- [x] Menu 导航菜单 inlineCollapsed 为 true， 首次 hover 渲染错误 #15717 
- [x] Sider初始在折叠状态，鼠标第一次移入SubMenu没有反应 #15776 
- [x] Collapsed Menu/MenuItem when selected does not consistently display the selected blue border on right #15819
- [x] inline Menu component flash and shake when collapsed #15853
- [x] Menu should be collapsed on start #15849
- [x] Layout中的Menu收缩的异常闪动 #15858

**Comment by ztplz** [comment]
mode的判断都乱掉了 menu revert to `3.14.1` ?
