### ISSUE TITLE
Bundle size optimization

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22698]
- [x] Replace `tinycolor2` in `@ant-design/colors`.
- [x] `@babel/runtime` and `babel-runtime`.
   - [x] 移除 `babel-runtime`。
   - [x] father 构建支持 `@babel/runtime`。
   - [x] fahter 3 support babel runtime version https://github.com/umijs/father/issues/224
   - [x] 底层 rc 组件迁移到 father 并开启 `@babel/runtime`。
     - [x] https://github.com/react-component/collapse
     - [x] ~https://github.com/react-component/animate~
     - [x] https://github.com/ant-design/css-animation
   - [x] antd 自身代码开启 `@babel/runtime`。
- [x] `core-js@2` and `core-js@3`. #16325
- [ ] `@ant-design/icons` unnecessary internal component.
- [x] Extra @babel/runtime helpers in @ant-design/icons https://github.com/ant-design/ant-design/pull/28678#issuecomment-754068217
- [x] `rc-util/lib/warning`
- [x] `components-classes` #23937
- [x] `package.json` version #23957
- [x] `react-lifecycles-compat` #23969 https://github.com/ant-design/ant-design/issues/24582
- [x] `add-dom-event-listener` https://github.com/ant-design/ant-design/issues/24582
- [x] `prop-types`
   - [x] `rc-menu` - `mini-store` https://github.com/yesmeck/mini-store/issues/10 https://github.com/yesmeck/mini-store/pull/11
   - [x] `rc-tabs` - `rc-hammerjs` https://github.com/ant-design/ant-design/pull/24552
   - [x] antd https://github.com/ant-design/ant-design/pull/24577
- [x] raf

##### IE polyfill

Not remove until IE out of support.

- [ ] Resize observer
- [ ] lodash/padStart
- [ ] lodash/padEnd

---

`npm run dist && open report.html` to see bundle size analyze reporter.

**Comment by ztplz** [comment]
I will start more optimization after April or May.

**Comment by afc163** [comment]
See if we can remove `add-dom-event-listener` from antd: https://github.com/react-component/util/blob/8e0e619de1147ef015dd8bc514fa461828f88cf5/src/Dom/addEventListener.js#L1

**Comment by muzea** [comment]
- @umijs/father default target IE10, will bring a lot of babel-runtime things, which is redundant for ES module (Under ES module, maybe can consider directly target chrome 61)
- Some components are not exported well, which makes tree shaking difficult (such as [field-form](https://github.com/react-component/field-form/blob/b48d379dd3fd79b24f86ff699e8bbc619462e7d2/src/index.tsx#L19-L28))

Recently I was trying to build a sexy gadget. However, I encountered many problems with antd, such as performance, many components will have useless rendering, and such as bundle size, a page with few functions will be 1.2M in size.

**Comment by Airkro** [comment]
https://github.com/ant-design/ant-design/issues/23096

**Comment by yoyo837** [comment]
Is it safe to remove the `raf` package now?

**Comment by afc163** [comment]
https://github.com/umijs/father/issues/224

**Comment by Airkro** [comment]
Replace [classnames](https://github.com/JedWatson/classnames) with [clsx](https://github.com/lukeed/clsx)

**Comment by muzea** [comment]
[![clsx](https://bundlephobia.com/api/stats-image?name=clsx&amp;version=1.1.1&amp;wide=true)](https://bundlephobia.com/result?p=clsx@1.1.1)

[![classnames](https://bundlephobia.com/api/stats-image?name=classnames&amp;version=2.2.6&amp;wide=true)](https://bundlephobia.com/result?p=classnames@2.2.6)

@Airkro 

The size of the two libraries is not much different, if you look at the comparison of the previous version, the difference is even smaller.

**Comment by Airkro** [comment]
`ConfigProvider` import whole `rc-field-form`. But not everyone uses `Form`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/28678

**Comment by Semigradsky** [comment]
There are no much differences in sizes between `classnames` and `clsx`. But `classnames` slower and looks like not maintained.
