### ISSUE TITLE
0.10.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#276]
### 总览

* 任务交付时间点：`2015-10-31`
* 发布时间点：`2015-11-13`
* 开发分支：https://github.com/ant-design/ant-design/tree/develop-0.10.0
* 关联 issues：https://github.com/ant-design/ant-design/milestones/0.10.0
* 需要设计支持：:art:

---

### 任务分解

- 新增组件
	- [x] :art: calendar #304 血诺@chentony   `视觉暂无 -@庆一 提供`
	- [x] :art: timepicker #305 天材@sinory   `视觉已有 -@青竾 跟进`
	- [x] :art: spin #315 乘五@KgTong  `视觉暂无 -@线丝 提供`
- 纯样式模块的组件化。
	- [x] button #306 本杰@benjycui 
	- [x] layout #308 展新@pizn 
	- [x] iconfont #307 南取@elrrrrrrr    
	- [x] form #309 再飞@simaQ 

- [x] :art: slider 增加双滑块功能。#323 本杰@benjycui  `视觉已有 -@线丝 跟进` 
- [x] :art: upload 视觉改进。#311 啸生@ikobe    `视觉改进 -@莘羽` 
- [x] :art: menu 视觉改进。#314 却痕@qiuyuntao    `视觉改进 -@庆一` 
- [x] popover 和 popconfirm 支持更多箭头位置。#312 贯高@popomore 
- [x] Table 列选择模式重构。#252 陆沉@RaoHai    
- [x] Table colspan 和 rowspan 支持。 react-component/table#11 勤拭@iyutao
- [x] antd-bin 代理功能。 ant-design/antd-bin#17 云谦@sorrycc 
- [x] antd-bin 单元测试功能。 ant-design/antd-bin#6 云谦@sorrycc 
- [x] antd-build 分离 build。 ant-design/antd-bin#16 云谦@sorrycc
- [x] 尝试支持 React 0.14.x 。#243  本杰@benjycui 
- [x] validation 和非原生组件的配合使用。#285 羽航@YuhangGe
- [x] tree 组件支持外部组件调用 #303 伯约@ioldfish 
- [x] iconfont 整体更换。#313 水鱼@zinkey   `视觉进行中 -@线丝`
- :art: datepicker 增加时间范围选择功能。#310 玉伯@lifesinger  `视觉已有 -@青竾 跟进`  移至 [0.11](https://github.com/ant-design/ant-design/issues/413)

---

### 参与方式

在此 issue 下留言，申请想参与的任务（后面没有 @ 人员的都可申请），等待 assign。

然后按照以下步骤参与开发：

1. 和 @afc163 和其他相关人员确定开发周期，沟通需求。
2. clone 本仓库到本地，从 `develop-0.10.0` 分支上切出一个新分支，分支命名按照 `feature-xxx` 来命名。
3. 按照 [网站和组件开发说明](https://github.com/ant-design/ant-design/wiki/%E7%BD%91%E7%AB%99%E5%92%8C%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%AF%B4%E6%98%8E) 进行本地开发调试，提交到自己的分支上（开发过程中建议经常 rebase `origin/develop-0.10.0` 分支）。
4. 完成开发，发起 [PR](https://github.com/ant-design/ant-design/compare/develop-0.10.0...xxxxxx) 到 `develop-0.10.0` 分支上，通知其他人进行 Review 。

### 职责

1. 主动按时负责完成对应任务的功能。
2. 代码风格良好，演示和文档简洁、完善、准确。
3. 配合代码 Review 和视觉 Review 进行任劳任怨地修改。

**Comment by afc163** [comment]
欢迎回复。

**Comment by demohi** [comment]
0.14版本的支持

**Comment by demohi** [comment]
Menu 菜单组件  增加item组的子组件  方便进行靠右处理。目前想实现菜单靠右比较困难

**Comment by CN-Sean** [comment]
1. 这些组件移动端效果如何？
2. table组件在大数据下除了分页，还可以滚动加载吗？移动端分页的交互很挫的。
3. 可以有下拉复选框组件吗，包括自定义值，模糊搜索这种的？
4. 既然面向企业级，大数据应该是重要考虑，下拉框也应该有滚动加载吧。包括组件的实际值和显示值等使用场景。
5. 日期控件的年月交互感觉比较复杂。我自己开源过一个jquery版本的，感觉交互的比你们简单了一层，仅供参考～ [Perfect-DateTimePicker](https://github.com/FineXs/Perfect-DateTimePicker)

**Comment by benjycui** [comment]
做个简单点的先，button

**Comment by sinory** [comment]
天材  timepicker

**Comment by KgTong** [comment]
乘五 spin

**Comment by elrrrrrrr** [comment]
南取 iconfont #307

**Comment by ikobe** [comment]
啸生 upload 视觉改进  #311

**Comment by benjycui** [comment]
像 button 这种纯样式模块组件化后，是直接把对应的目录下的 *.md，如 `components/button/index.md` 覆盖掉还是？

**Comment by afc163** [comment]
@benjycui  对，在保持原有演示功能的前提下，直接修改掉就好。

**Comment by RaoHai** [comment]
认领 #252 Table 列选择模式重构，正好自己也有类似需求。

**Comment by ioldfish** [comment]
#303 我领了

**Comment by YuhangGe** [comment]
#323 羽航

**Comment by qiuyuntao** [comment]
却痕 #314

**Comment by YuhangGe** [comment]
#285 羽航

**Comment by popomore** [comment]
领 #312

**Comment by janlay** [comment]
领 #312

**Comment by lifesinger** [comment]
领一个 #310

**Comment by zinkey** [comment]
体力活 #313

**Comment by iyutao** [comment]
这个[Table colspan 和 rowspan 支持](https://github.com/react-component/table/issues/11)没人认领吗？我来试试

**Comment by afc163** [comment]
赞赞赞，就是你了。

**Comment by afc163** [comment]
## 新组件开发流程

1. 先开发相应的 React 组件（如果需要的话）。[开发方式](https://github.com/react-component/react-component.github.io/blob/master/docs/zh-cn/how-to-write-a-react-component.md)
2. 将组件接入到 Ant Design。（可以参考 [datepicker](http://ant.design/components/datepicker/)）
   1. 克隆仓库到本地 https://github.com/ant-design/ant-design 并启动本地开发环境。
   2. 引入组件 `tnpm install rc-calender --save` 和其他必要依赖。
   3. 在[项目主文件](https://github.com/ant-design/ant-design/blob/master/index.js)里引入，并放到 antd 上（先暴露到 window 方便调试，后续再改）。
   4. 在 [Components 目录里的对应坑位](https://github.com/ant-design/ant-design/tree/master/components/datepicker) 建立对应文件。
   5. `index.jsx` 用于二次封装（如果已有组件太复杂的，建议只保留最基础的参数），`index.md` 是项目文档，`demo` 目录放置演示实例。具体写法参考 [datepicker](https://github.com/ant-design/ant-design/tree/master/components/datepicker)。
   6. 样式请统一写在 https://github.com/ant-design/ant-design/tree/master/style 中，具体写法和用法询问 @zaifei.zwx 。
   7. 本地完成开发调试，确保演示和文档完整，`tnpm run deploy` 部署到 http://ant.design 上。

**Comment by elrrrrrrr** [comment]
麻烦 @afc163 添加一下 react-component 权限

**Comment by chentony** [comment]
血诺 #304

**Comment by elrrrrrrr** [comment]
iconfont 接入方式有变，麻烦大家回归一下
!361

**Comment by afc163** [comment]
#306 #307 已完成~

**Comment by afc163** [comment]
视觉稿缺失可以主动联系相关设计师索要。

**Comment by benjycui** [comment]
Button 接入方式有变，麻烦大家回归一下 #368

**Comment by benjycui** [comment]
本杰 #243 进行中，感觉需要各组件的开发者配合。

**Comment by lifesinger** [comment]
大家及时跟进，给自己也加把油。

**Comment by afc163** [comment]
大家都注意下 IE8/9 的兼容性。https://github.com/ant-design/ant-design/issues/456
