### ISSUE TITLE
v5 Task List

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#34087]
ref #33862

# Task List

🚨 Note: Volunteer will be removed if long time not update.

## Preparation
- [x] New Design Token @zombieJ 
  - [x] v5 Design Token  @arvinxx
  - [x] Viewable Default Theme @zombieJ 
- [x] CSSINJS @zombieJ 
  - [x] SSR support @zombieJ 
  - [x] Component: Button @zombieJ https://github.com/ant-design/ant-design/pull/33890
    - [x] Full Token #34690
  - [x] Component: Affix @LongHaoo  #34558
    - [x] Full Token (no need)
  - [x] Component: Divider @LongHaoo   #34364
    - [x] Full Token #34713
  - [x] Component: Anchor @LongHaoo #35139
    - [x] Full Token #35588
  - [x] Component: Icon @LongHaoo   #35346
    - [x] Full Token (no need)
  - [x] Component: BackTop @LongHaoo #34882
    - [x] Full Token #35599
  - [x] Component: Empty @LongHaoo   #34842
    - [x] Full Token 
  - [x] Component: Space @0x219 #35211
    - [x] Full Token (no need)
  - [x] Component: Typography @afc163   https://github.com/ant-design/ant-design/pull/34372
    - [x] Full Token #34713
  - [x] Component: Upload @afc163  🤖  https://github.com/ant-design/ant-design/pull/34528
    - [x] Full Token #35617
  - [x] Component: Carousel @afc163   https://github.com/ant-design/ant-design/pull/34634
    - [x] Full Token #35624
  - [x] Component: Table @afc163  #35584
    - [x] Full Token #35888
  - [x] Component: Checkbox  @zombieJ   #34247
    - [x] Full Token #34713
  - [x] Component: Select @zombieJ   #34339
    - [x] Full Token #34713
  - [x] Component: Tree @zombieJ   #34258
    - [x] Full Token #34713
  - [x] Component: TreeSelect @zombieJ   #34383
    - [x] Full Token #34713
  - [x] Component: Layout @zpc7 #35102
    - [x] Full Token #35628
  - [x] Component: Menu @heiyu4585 #34958
    - [x] Full Token #35650
  - [x] Component: Dropdown @zombieJ  #35214
  - [x] Component: AutoComplete @zombieJ  #34339
    - [x] Full Token #34713
  - [x] Component: Cascader @zombieJ  #34374
    - [x] Full Token #34766
  - [x] Component: Slider @zombieJ  #34489
    - [x] Full Token #34766
  - [x] Component: Input @MadCcc  https://github.com/ant-design/ant-design/pull/34288
    - [x] Full Token #34766
  - [x] Component: TextArea @MadCcc https://github.com/ant-design/ant-design/pull/34484
    - [x] Full Token #34766
  - [x] Component: InputNumber @MadCcc  https://github.com/ant-design/ant-design/pull/34384
    - [x] Full Token #34766
  - [x] Component: DatePicker @MadCcc https://github.com/ant-design/ant-design/pull/35037
    - [x] Full Token #35615  
  - [x] Component: TimePicker @MadCcc https://github.com/ant-design/ant-design/pull/35037
    - [x] Full Token #35615  
  - [x] Component: Mentions @MadCcc  #34536
    - [x] Full Token #34766
  - [x] Component: Form @MadCcc  #34679
  - [x] Component: Alert @xrkffgg https://github.com/ant-design/ant-design/pull/34285
    - [x] Full Token #35702
  - [x] Component: Popover @xrkffgg  https://github.com/ant-design/ant-design/pull/34607
    - [x] Full Token #35712
  - [x] Component: Avatar @xrkffgg  https://github.com/ant-design/ant-design/pull/34737
    - [x] Full Token #35764
  - [x] Component: Collapse @xrkffgg https://github.com/ant-design/ant-design/pull/35066
    - [x] Full Token #35789
  - [x] Component: Tag @vagusX https://github.com/ant-design/ant-design/pull/34422
    - [x] Full Token #35830
  - [x] Component: Result @vagusX https://github.com/ant-design/ant-design/pull/34317
    - [x] Full Token #35834
  - [x] Component: Radio  @vagusX https://github.com/ant-design/ant-design/pull/34740
    - [x] Full Token #35838
  - [x] Component: Segmented @vagusX #34319 #35134
    - [x] Full Token #35845
  - [x] Component: Badge @iamkun https://github.com/ant-design/ant-design/pull/34386
    - [x] Full Token #35858
  - [x] Component: Statistic @iamkun https://github.com/ant-design/ant-design/pull/34514
    - [x] Full Token #35877
  - [x] Component: Transfer @miracles1919 #35508
    - [x] Full Token #35882
  - [x] Component: Tooltip @zpc7  #35340 
    - [x] Full Token #35896
  - [x] Component: Tabs  @miracles1919  #34811
    - [x] Full Token #35891
  - [x] Component: Rate @PeachScript  #34373
    - [x] Full Token #35886
  - [x] Component: Switch @PeachScript #34517
    - [x] Full Token #35873 
  - [x] Component: Pagination @PeachScript #34661 
    - [x] Full Token #35872 
  - [x] Component: Breadcrumb @PeachScript 🤖 #35125
    - [x] Full Token #35868 
  - [x] Component: Skeleton @heiyu4585 #34698
    - [x] Full Token #35866
  - [x] Component: Steps @zpc7 #35058
    - [x] Full Token #35841
  - [x] Component: Grid  🚀 @JiquanWang99  #34573
    - [x] Full Token #35847
  - [x] Component: Spin  🚀 @jrr997 #34653   https://github.com/ant-design/ant-design/issues/34087#issuecomment-1066523999 
    - [x] Full Token #35746 
  - [x] Component: Progress  @shuaijiumei  #34692
    - [x] Full Token #35745
  - [x] Component: Descriptions 🚀 @Dunqing  #34786
    - [x] Full Token #35697
  - [x] Component: Timeline @LuZhenJie1999 #34980
    - [x] Full Token #35686
  - [x] Component: Message  @TrickyPi #35565
    - [x] Full Token #35741  
  - [x] Component: Notification @zpc7  #35559
    - [x] Full Token #35656 
  - [x] Component: Popconfirm   #35683
    - [x] Full Token perfectly done 🚀
  - [x] Component: Calendar @Dunqing #34835
    - [x] Full Token #35615  
  - [x] Component: Drawer   🚀 @heiyu4585  #34656
    - [x] Full Token #35596 
  - [x] Component: List @heiyu4585 #34739
    - [x] Full Token #35571 
  - [x] Component: Modal  @foryuki #35260 
    - [x] Full Token #35477
  - [x] Component: Image 🚀 @heiyu4585 #34630
    - [x] Full Token #35465 
  - [x] Component: Card @miracles1919  #35008
    - [x] Full Token #35514 

## <a id="alpha">Validation Version (Alpha)</a>

> This version used for validation which is not aim to work on production. And not promise api will be the same as major version.

- [x] Production warning #36194
  - [x] [Issue](https://github.com/ant-design/ant-design/issues/33862) update 
- [x] v4 Theme validation
  - [x] Light Theme
  - [x] Dark Theme
- [x] RM less file
- [x] Third part cssinjs extension (ProComponents)(`useToken` only)
- [x] Theme Previewer seed support
- [x] Dumi ConfigProvider injection

## Available Version
- [x] Theme
  - [x] Default Theme Algorithm @arvinxx
  - [x] Dark Theme Algorithm @arvinxx
  - [x] Compact Theme Algorithm @arvinxx
  - [x] V4 Theme @MadCcc
- [x] ProComponent use v5 token @chenshuai2144 
  - [x] One sample component @MadCcc 
- [x] Refactor @zombieJ 
  - [x] [Popup related component provide unique panel component](https://github.com/ant-design/ant-design/wiki/Unique-Panel-Component)
    - [x] API design @arvinxx
    - [x] Modal #36012
    - [x] Drawer
    - [x] Popconfirm @caoj1993
    - [x] Notification @zombieJ  #35948
    - [x] Message @zombieJ 
  - [x] Move all className on the top of DOM (e.g. Image) @MadCcc 
- [x] day.js replacement @iamkun https://github.com/ant-design/ant-design/pull/34057
  - [x] Document Update @iamkun #35935
- [ ] Control component trade `null` as empty value #34437 @shezhangzhang
- [ ] Component cutoff
  - [x] Remove Strcutrue Syntactic Sugar
    - [x] TreeSelect @heiyu4585 #37622
    - [x] select @heiyu4585 #37601
    - [x] Tree  @heiyu4585 #37626 
    - [x] AutoComplete @heiyu4585 #37592
    - [x] Cascader
    - [x] Dropdown
    - [x] Menu
    - [x] Mentions @heiyu4585 #38630 
    - [x] Table
  - [x] Refactor Picker generator to Function component @heiyu4585 #35425 
  - [ ] Table `colums.render` only support returning ReactNode
  - [x] Replace all `dropdownClassName` with `popupClassName` @heiyu4585  https://github.com/ant-design/ant-design/issues/37326
- [x] Compatible package  @vagusX
- [x] Alpha app test @@iamkun
- [x] Move to ProComponent: @chenshuai2144 
  - [x] PageHeader @chenshuai2144 
  - [x] Comment @chenshuai2144 
  - [x] compatible package
- [x] Remove antd/lib/xxx, ESM only
    - [x] Remove babel-plugin-import warning `You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.`
- [x] DatePicker support sidebar https://github.com/ant-design/ant-design/issues/36860
- [x] New Component
  - [x] WaterMark
  - [x] Tour https://github.com/ant-design/ant-design/pull/37867
  - [x] QrCode
  - [x] Floating Button https://github.com/ant-design/ant-design/issues/12738

<div id="release" />

## Release

- [x] Compatible Package
  - [x] v4 theme
    - [x] dark
    - [x] default
  - [x] less file  @zombieJ 
- [x] Codemod
- [x] Theme: default, dark, compact
- [x] Site Related
  - [x] Official Site   @zombieJ  @MadCcc  @li-jia-nan 
  - [x] PreRender  @PeachScript 
  - [x] Link 404 @PeachScript 
  - [x] Changelog  @MadCcc 
  - [x] Migrate guid @MadCcc 
  - [x] 4x Site @MadCcc 
  - [x] Home page recommend with v5 blog ref
- [x] Remove css variables & less file
- [x] Theme Editor @MadCcc 
- [x] dayjs 替换 moment
- [x] Blog: v5 release
  - [x] Chinese blog release
  - [x] English blog release
- [x] Package publish

## After Release

- [ ] V5 Blog
  - [ ] Components level css-in-js
- [ ] New components
  - [x] Tour
  - [x] Progress
  - [x] Circle
  - [x] DatePicker
  - [x] FloatButton
  - [x] Steps
  - [ ] WaterMark
  - [ ] QRCode
  - [ ] ColorPicker 
- [ ] Close v4 PR

## Both Benefit

- [x] Convert Testing Lib #37229
  - [x] ConfigProvider @li-jia-nan  #37142
  - [x] _util/__tests__ @li-jia-nan  #37155
  - [x] Component: Button @Carrotzpc #35869
  - [x] Component: Affix @zggmd #35860
  - [x] Component: Divider @jrr997 #35326
  - [x] Component: Anchor @linqiqi077 #35371
  - [x] Component: Icon
  - [x] Component: BackTop @foryuki #35909
  - [x] Component: Empty @lalalazero #35289
  - [x] Component: Space @jrr997 #35372
  - [x] Component: Typography @yykoypj #35955
  - [x] Component: Upload @yykoypj #36024
  - [x] Component: Carousel @yykoypj #35926
  - [x] Component: Table @poyiding #35925 #35989
  - [x] Component: Checkbox @TrickyPi #35354
  - [x] Component: Select @heiyu4585 #35633
  - [x] Component: Tree @dancerphil #35674
  - [x] Component: TreeSelect @li-jia-nan #37190
  - [x] Component: Layout  #36323
  - [x] Component: Menu @poyiding #37046
  - [x] Component: Dropdown @foryuki #37003
  - [x] Component: AutoComplete @foryuki #35900
  - [x] Component: Cascader @poyiding #36475
  - [x] Component: Slider @0x219 #36888
  - [x] Component: Input @zhengshuai1001 #35754
  - [x] Component: TextArea 
  - [x] Component: InputNumber @heiyu4585 #36080
  - [x] Component: DatePicker @li-jia-nan #37115
  - [x] Component: TimePicker @li-jia-nan  #37055
  - [x] Component: Mentions @li-jia-nan #36998 
  - [x] Component: Alert @Shezhangzhang #35736
  - [x] Component: Popover @li-jia-nan #36997 
  - [x] Component: Avatar @yykoypj #35791
  - [x] Component: Collapse @foryuki #36227
  - [x] Component: Tag @vagusX #35783
  - [x] Component: Result @vagusX #35621
  - [x] Component: Radio @cwjTerrace #36664
  - [x] Component: Segmented @vagusX #35538
  - [x] Component: Badge @foryuki #36033
  - [x] Component: Statistic @foryuki #36019 #36034
  - [x] Component: Tooltip @zpc7 #35396
  - [x] Component: Tabs #35796
  - [x] Component: Rate
  - [x] Component: Switch @foryuki #36326
  - [x] Component: Pagination #36178
  - [x] Component: Breadcrumb #36276
  - [x] Component: Skeleton @foryuki #36856
  - [x] Component: Steps @heiyu4585 #37042 
  - [x] Component: Grid @foryuki #37057
  - [x] Component: Spin @foryuki #36317
  - [x] Component: Progress
  - [x] Component: Descriptions @li-jia-nan #36970
  - [x] Component: Timeline @jrr997 #35654
  - [x] Component: Message @0x219 #36923
  - [x] Component: Notification @0x219 #36924
  - [x] Component: Drawer @yykoypj #35839
  - [x] Component: List @yykoypj #35850
  - [x] Component: Modal @foryuki #35785
  - [x] Component: Image @yykoypj #35806
  - [x] Component: Card @LongHaoo #35751
  - [x] Component: Affix @RexSkz #37299 
  - [x] Component: Avatar @li-jia-nan #37266 
  - [x] Component: menu @li-jia-nan  #37274  
  - [x] Component: message @li-jia-nan #37256
  - [x] Component: notification @li-jia-nan #37253 
  - [x] Component: Tag @vagusX #35783
  - [x] Component: Transfer @LiHaoGit #37029 
  - [x] Component: PageHeader @li-jia-nan #37218 
  - [x] demoTest function @heiyu4585 @zombieJ #37381
  - [x] focusTest function @heiyu4585 #37280 
  - [x] rtlTest function @li-jia-nan #37315 
  - [x] Component: Calendar @lzm0x219  #37704  
  - [x] Component: form @li-jia-nan #37727 
  - [x] Component: Popconfirm @lzm0x219  #37703 
  - [x] setup.js @li-jia-nan #37854 
- [ ] React 18 Support
  - [x] Base test case support #34787
  - [x] Site support StrictMode #34895
  - [ ] Concurrent support

## <a id="join">Join Ding group to contribute</a>

🚨 为确保加入同学对开源社区有参与兴趣，加入请贴上一则在 [ant-design](https://github.com/ant-design) 或 [react-component](https://github.com/react-component) 上贡献的 PR 地址。反之，入群申请会被拒绝。

🚨 In order to ensure that students who join are interested in participating in the open source community, please post a post in [ant-design](https://github.com/ant-design) or [react-component](https://github.com/react-component) contributed PR address. Otherwise, the application to join the group will be rejected.

<img src="https://user-images.githubusercontent.com/5378891/170645293-70f606ed-5508-4107-929f-72dea9da6b03.jpg" width="200" />

**Comment by afc163** [comment]
- [ ] New Component
  - [ ] WaterMark
  - [ ] Tour
  - [ ] QrCode
  - [ ] Floating Button https://github.com/ant-design/ant-design/issues/12738

**Comment by DreamPWJ** [comment]
https://github.com/ant-design/ant-design/issues/31399   这个组件很需要要, 不考虑新增吗？@afc163

**Comment by yoyo837** [comment]
React 17 full support?

**Comment by xrkffgg** [comment]
@zombieJ PR 链接也加上，这样我也可以参照你的 改改~

**Comment by kaoding** [comment]
有v5的发布时间吗？

**Comment by chessl** [comment]
I can volunteer for some easy ones, @zombieJ you cloud assign me a few you feel comfortable with.  😛

**Comment by zombieJ** [comment]
> I can volunteer for some easy ones, @zombieJ you cloud assign me a few you feel comfortable with.  😛

wow. Thanks for volunteer. Let me pick one for you.

**Comment by zombieJ** [comment]
> I want to join this plan and help to do some easy tasks, but I don't have too much experience doing open source component library, can I ?

Thanks for volunteer. You can try Grid component : )
Let me hold this component

**Comment by wsxe9988** [comment]
V5   Regarding modal, you can increase the size of 8 methods such as up, down, left, and right

**Comment by wsxe9988** [comment]
datepicker组件支持日期多选

**Comment by wsxe9988** [comment]
v5版今年会release么

**Comment by PeachScript** [comment]
@wsxe9988 这里只讨论 v5 的任务情况，其他 v5 相关问题可以在 #33862 里查找或讨论，另外 feature request 请单独提 issue

**Comment by ice-zjchen** [comment]
May I try `Descriptions` component? @zombieJ

**Comment by zombieJ** [comment]
@ice-zjchen , sure. Let me mark the component~

**Comment by jrr997** [comment]
I would like to help, can you pick me  a easy one ? @zombieJ

**Comment by heiyu4585** [comment]
I would like to help, can you pick me a easy one ? @zombieJ

**Comment by yoyo837** [comment]
感觉，有兴趣的可以先留言自行认领某一个，Owner 确认后标记。

**Comment by heiyu4585** [comment]
> 感觉，有兴趣的可以先留言自行认领某一个，Owner 确认后标记。

那我想先认领一个:,个人认为简单一点

-  CSSINJS 
  - - Component: Avatar

**Comment by zombieJ** [comment]
@heiyu4585 后面有 @ or [HOLD] 的人是已经 assign 过 task 的了，你可以在下面没有 @ 的 component 里再调一调

**Comment by heiyu4585** [comment]
> @heiyu4585 后面有 @ or [HOLD] 的人是已经 assign 过 task 的了，你可以在下面没有 @ 的 component 里再挑一挑

那我选  `Component: Image`

**Comment by jrr997** [comment]
我可以选`Component: Spin`吗 @zombieJ

**Comment by yoyo837** [comment]
以上, 已加 `[HOLD]`.

**Comment by heiyu4585** [comment]
Image 组件的弹窗 是否属于下列类型,需要等待API设计完成后,

- [ ]  Refactor @zombieJ
   - [x]  Popup related component provide unique panel component
      - [x]  API design @arvinxx

**Comment by zombieJ** [comment]
@JiquanWang99  @ice-zjchen   @jrr997   @heiyu4585   加一下钉钉群，有问题可以直接问我哈：

![image](https://user-images.githubusercontent.com/5378891/158573375-13b23eda-bb6c-4b42-8dd4-6926b0018ca8.png)

**Comment by heiyu4585** [comment]
@zombieJ  提示'团队邀请已关闭'

**Comment by zombieJ** [comment]
> @zombieJ 提示'团队邀请已关闭'

Updated~

**Comment by yoyo837** [comment]
> React 17 full support?

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

React 18 RC is out, do we follow it?

**Comment by heiyu4585** [comment]
> 以上pick，已加`[HOLD]`。

`Drawer` 我继续跟进下可以吗 @yoyo837

**Comment by miracles1919** [comment]
pick `Component: Notification`  先试试

**Comment by zombieJ** [comment]
@miracles1919 , Notification 有静态方法，你先试试 Tabs 吧~

**Comment by 1247748612** [comment]
I want to participate, what can I do?

**Comment by zombieJ** [comment]
> I want to participate, what can I do?

@1247748612, pls feel free to join DingDing group for tasks : )

**Comment by zombieJ** [comment]
hi @ice-zjchen , since long time no update, we've make Descriptions as volunteer again. Pls feel free if any feedback. Thanks : )

**Comment by zombieJ** [comment]
@1247748612 , 
Welcome, assign as Descriptions : )

**Comment by lalalazero** [comment]
豆酱老师我也想参与，我看 Modal cssinjs 还没有分，可以分给我吗？

**Comment by zombieJ** [comment]
> 豆酱老师我也想参与，我看 Modal cssinjs 还没有分，可以分给我吗？

@lalalazero，先加入 v5 共建群哈~

**Comment by zombieJ** [comment]
#### Resting CSSINJS pending
* Table
* Breadcrumb
* Message
* Popconfirm

**Comment by zhenzhenChange** [comment]
`Tabs`组件的`activeKey`能否支持泛型？例如在`TS`下用了枚举，不然的话一般需要断言

![image](https://user-images.githubusercontent.com/51586637/169479886-f32f8e1a-95ee-4d28-bedc-70a5aa24940d.png)

![image](https://user-images.githubusercontent.com/51586637/169479920-afc1d0e3-18f4-41f0-b036-66d48bf4fe3e.png)

![image](https://user-images.githubusercontent.com/51586637/169479946-f49a8c59-1f23-4682-b6d7-13079b68740d.png)

**Comment by aShen-onei** [comment]
#35820 大佬这个什么时候更新哇😭

**Comment by MadCcc** [comment]
> #35820 大佬这个什么时候更新哇😭

@aShen-onei 目前的解决方案是把 columns 写在 render 里，这里的 task 都是会跟着 v5 发布的

**Comment by afc163** [comment]
- [ ] Upgrade to react 18 in workflow

**Comment by ZWkang** [comment]
@zombieJ  I want to join, could you pick some tasks to me please?
