### ISSUE TITLE
迁移 enzyme 至 test-lib

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#37229]
### What problem does this feature solve?

为了过渡到 v5，我们需要将 v4 中所有涉及到 `enzyme` 的组件全部迁移到 `testing-library`

在 [V5 Task List](https://github.com/ant-design/ant-design/issues/34087) 中，我们已经将大部分 `enzyme` 迁移完毕，这里只做最后的 **补充** 和 **走查**：

#### PR List:

- [x] Calendar @lzm0x219  #37704 
- [x] Popconfirm @lzm0x219  #37703 
- [x] Affix @RexSkz #37299 
- [x] form @li-jia-nan #37727 
- [x] menu @li-jia-nan  #37274  
- [x] Avatar @li-jia-nan #37266 
- [x] message @li-jia-nan #37256
- [x] notification @li-jia-nan #37253 
- [x] PageHeader @li-jia-nan #37218 
- [x] rtlTest function @li-jia-nan #37315 
- [x] demoTest function @heiyu4585 @zombieJ #37381
- [x] Tag @vagusX #35783
- [x] Transfer @LiHaoGit #37029 
- [x] focusTest function @heiyu4585 #37280 
- [x] setup.js @li-jia-nan  #37854

**Comment by 0x219** [comment]
😼

**Comment by li-jia-nan** [comment]
@zombieJ 完结撒花～🎉
