### ISSUE TITLE
v5 site upgrade

### ISSUE THREAD

**Issue by PeachScript** [ant-design/ant-design#37880]
ref: https://github.com/ant-design/ant-design/issues/34087

## Preparation for Contribute
- Base branch: [v5-site-upgrade](https://github.com/ant-design/ant-design/tree/v5-site-upgrade)
- Doc framework: [dumi 2.0](https://next.d.umijs.org/) (v5 target), [Bisheng](https://github.com/benjycui/bisheng) (v4 used)
- dumi 2.0 theme system: https://github.com/umijs/dumi/discussions/1180
- Tasks targets:
  1. Migrate Bisheng to dumi 2.0
  3. Rewrite theme according to v5 site design
- ‼️ Tasks explanations:
  1. `from` links to the legacy code, `to` links to the target file that should to be programmed
  2. `Design` sub task means that the `Code` sub task can be start after design ready

## Contribution steps
1. Clone repo and checkout a self branch from the base branch
2. `npm i`
4. `npm start` & open `http://localhost:8000`
5. Coding & testing
6. Push & create a pull request to the base branch

### Layout
- [ ] Migrate `ConfigProvider`, Dynamic Theme & etc. to `GlobalLayout` @MadCcc 
- [x] Migrate `Layout` to `DocLayout` @PeachScript 
- [x] Migrate `Header` @MadCcc 
  - <img width="1536" alt="header" src="https://user-images.githubusercontent.com/5035925/194592028-491f63fd-092e-43ba-9e14-a23e5cab9a78.png">
  - [x] Design
  - [x] Code ([from](https://github.com/ant-design/ant-design/blob/7846d69bbf7ded0c46fd90041470bb16303145e9/site/theme/template/Layout/Header/index.tsx) -> [to](https://github.com/ant-design/ant-design/blob/490a33acd9e8021c731fa8f8a36ecca20478a33c/.dumi/theme/slots/Header/index.tsx))
    - Navbar
    - Search bar
    - GitHub link
    - RTL button
    - Language switch
    - ...
- [x] Migrate `Sidebar` @MadCcc 
  - <img width="321" alt="Sidebar" src="https://user-images.githubusercontent.com/5035925/194592314-d8c03000-b46b-4577-9c46-4c2094741933.png">
  - [x] Design
  - [x] Code ([from](https://github.com/ant-design/ant-design/blob/2a754bd5cad7fd4892a065a8e044fb402f51f426/site/theme/template/Content/MainContent.jsx#L458-L467) -> [to](https://github.com/ant-design/ant-design/blob/490a33acd9e8021c731fa8f8a36ecca20478a33c/.dumi/theme/slots/Sidebar/index.tsx))
    - Sticky
    - Menu Group & Menu Item
    - Collapsible (only for [design doc](https://ant.design/docs/spec/introduce-cn))
    - ...
- [x] Migrate `Footer` @MadCcc 
  - <img width="1161" alt="footer" src="https://user-images.githubusercontent.com/5035925/194593120-ae9be3e4-a1ab-4bff-b500-9b14451c5055.png">
  - [ ] Design
  - [ ] Code ([from](https://github.com/ant-design/ant-design/blob/c9ea74299a54009b978b72212fe272f10ff640c2/site/theme/template/Layout/Footer.tsx) -> [to](https://github.com/ant-design/ant-design/blob/c9ea74299a54009b978b72212fe272f10ff640c2/site/theme/template/Layout/Footer.tsx))

### Custom pages
- [ ] Migrate `/index` page @zombieJ 
  - [ ] Design
  - [x] Code ([from](https://github.com/ant-design/ant-design/blob/2804cb843a1f6d8b46e44e13c2552f34c487b797/site/theme/template/Home/index.tsx) -> [to](https://github.com/ant-design/ant-design/blob/96e7ad5e33f660c9ff5e841a677ba91c541da1b2/.dumi/pages/index/index/index.tsx))

### Layout
- [x] Migrate `Content`
  - <img width="976" alt="content" src="https://user-images.githubusercontent.com/5035925/194592423-d6e51207-3cd8-441e-b82d-fe0e4c0bcbd2.png">
  - [x] Design
  - [x] Code ([from](https://github.com/ant-design/ant-design/blob/2a754bd5cad7fd4892a065a8e044fb402f51f426/site/theme/template/Content/MainContent.jsx) -> [to](https://github.com/ant-design/ant-design/blob/490a33acd9e8021c731fa8f8a36ecca20478a33c/.dumi/theme/slots/Content/index.tsx))
    - Title & edit link
    - TOC
    - Contributors list
    - Prev & next page
    - ...

### Custom Components
- [ ] Migrate `Previewer`
  - <img width="500" alt="previewer" src="https://user-images.githubusercontent.com/5035925/194593336-991ef55b-7854-40ee-9eaa-feb2ae09b817.png">
  - [x] Basic migrate @PeachScript 
  - [ ] Refactor with dumi way (remove the [compatibility HOC](https://github.com/ant-design/ant-design/blob/cf9425c98fc28a50f4e54b34816db90649fc3c1f/.dumi/theme/builtins/Previewer/fromDumiProps.tsx))
- [x] Create `DemoWrapper` ([from](https://github.com/ant-design/ant-design/blob/86891775dd6deb4e154b885718a370d31bc78288/site/theme/template/Content/ComponentDoc.jsx#L187-L214) ->  [to](https://github.com/ant-design/ant-design/blob/490a33acd9e8021c731fa8f8a36ecca20478a33c/.dumi/theme/builtins/DemoWrapper/index.tsx)) @zqran 
  - <img width="116" alt="demo-wrapper" src="https://user-images.githubusercontent.com/5035925/194592545-97d79b0e-7a8c-4978-a535-ed90d697b273.png">
  - Expand source code for all previewer
  - Display debug demo
- [x] Create `IconSearch` ([from](https://github.com/ant-design/ant-design/blob/c9ea74299a54009b978b72212fe272f10ff640c2/site/theme/template/IconDisplay/index.tsx) -> [to](https://github.com/ant-design/ant-design/blob/490a33acd9e8021c731fa8f8a36ecca20478a33c/.dumi/theme/builtins/IconSearch/index.tsx)) @TrickyPi
  - <img width="1073" alt="icon-search" src="https://user-images.githubusercontent.com/5035925/194592710-ac1f3e0c-fb5c-4182-8f8c-63aed8f1425a.png">
- [x] [PENDING] Components that depend on the new markdown data structure ready:
  - [ ] New data structure to describe markdown content for `ResourceCard`, `APITable` & etc. @zombieJ @MadCcc 
  - [x] Create `ResouceCard`
    - <img width="1225" alt="resource-card" src="https://user-images.githubusercontent.com/5035925/194592829-7b771ff7-9d07-444b-987a-e5a562b0ada9.png">
    - [x] Design
    - [x] Code
  - [x] #38180
    - <img width="995" alt="api-table" src="https://user-images.githubusercontent.com/5035925/194592933-3629470d-3f1c-449d-8306-c982ea8452ca.png">
    - [ ] Design
    - [ ] Code

### Custom pages
- [x] Migrate `/components/overview` page ([from](https://github.com/ant-design/ant-design/blob/44d8e382bae77b82915effba051af58efd3d0551/site/theme/template/Content/ComponentOverview.jsx) -> [to](https://github.com/ant-design/ant-design/blob/96e7ad5e33f660c9ff5e841a677ba91c541da1b2/.dumi/pages/theme/builtin/Overview/index.tsx)) @li-jia-nan #38131  
- [x] Migrate `/changelog` page ([from](https://github.com/ant-design/ant-design/blob/2a754bd5cad7fd4892a065a8e044fb402f51f426/site/theme/template/Content/MainContent.jsx#L35) -> [to](https://github.com/ant-design/ant-design/blob/96e7ad5e33f660c9ff5e841a677ba91c541da1b2/.dumi/pages/changelog/index.tsx)) @li-jia-nan #38137 #38162 
- [x] Migrate `404` page ([from](https://github.com/ant-design/ant-design/blob/0067b923b998eb8e68748a7c5b6f9414fb819052/site/theme/template/NotFound.tsx) -> [to](https://github.com/ant-design/ant-design/blob/96e7ad5e33f660c9ff5e841a677ba91c541da1b2/.dumi/pages/404/index.tsx)) @zqran #38118 

### Compile-time plugin
- [ ] `rehypeAntd` plugin:
  - [ ] Transform demo tsx to jsx via https://github.com/umijs/sylvanas ([from](https://github.com/ant-design/bisheng-plugin-antd/blob/master/src/process-demo.js) -> [to](https://github.com/ant-design/ant-design/blob/2d4624bb9b66d6c5434637cc4e8eea42b81dba10/.dumi/plugin.ts#L24-L25))
  - [ ] Compile markdown content to the new data structure (depends on data structure task completion) @PeachScript 
- [ ] dumi plugin:
  - [ ] Register tab ui to display design/code to a single page (depends on dumi tab solution ready) @PeachScript

**Comment by TrickyPi** [comment]
> ## Contribution steps
> 1. Clone repo and checkout a self branch from the base branch
> 2. `npm i`
> 3. `npm run start:dumi` & open `http://localhost:8000`
> 4. Coding & testing
> 5. Push & create a pull request to the base branch

第三步的`npm run start:dumi`应该改成了`npm run start`了吧
