### ISSUE TITLE
0.11.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#413]
开发分支：https://github.com/ant-design/ant-design/tree/develop-0.11.0

预计发布时间：`2015-12-25`。

所有提交：https://github.com/ant-design/ant-design/compare/0.10.4...develop-0.11.0

### 特性列表：

- [x] 移除默认加载的样式文件，样式需要独立加载 #567
- [x] :art: dashed button 添加虚线型按钮
- [x] :art: 添加和关闭 tabs 的样式（新型的 tabs）#674
- [x] table 去除远程模式 #651
- [x] :art: Table filter 样式调整
- [x] :art: 按钮样式调整，圆角调整为 6px 
- [x] :art: 通用搜索框样式 
- [x] :art: select 选中样式调整
- [x] :art: 时间范围选择控件。#310 @benjycui
- [x] :art: 设计资源下载页面
- [x] webpack2 和 babel6 跟进
- [x] Modal popconfirm 等组件的文案国际化 #575
- [x] :art: 紧凑型表格
- [x] :art: 穿梭框 transfer：https://github.com/ant-design/ant-design/tree/component-transfer @dqaria 
- [x] :art: 调整警告和错误状态色
- [x] :art: 简单分页样式调整 @ibigbug 
       ![](https://os.alipayobjects.com/rmsportal/BMbSXJFRToMnTOd.png)
- [x] :art: 吊顶规范
- [x] :art: alert 默认不显示图标
- [x] dropdown button：带菜单触发的按钮
- [x] 小号 switch
- [x] upload 列表添加图片文件样式
- [x] Datepicker => DatePicker & Timepicker => TimePicker
- [x] 独立使用的 Badge 8a69058

### 发布前还需要做的事：

- [x] ~~首页改版 @jljsj33~~
- [x] rc-timepicker rc-slider  rc-calendar 依赖升级，相关演示调整接入
- [x] 010x.ant.design 旧版网站部署
- [x] changelog 和 upgrade 文档书写 #700

**Comment by bang88** [comment]
@afc163  `Table` 去除远程模式 这个会在将来移除？

**Comment by Chinglik** [comment]
本期视觉已跟新的组件和样式细节罗列如下，请前端同学安排开发计划：

* 小列表样式 [高度为38px]
* 小列表包含小分页的样式
* 穿梭框
* 按钮大圆角修改为6px圆角
* 优化select的选择方式
* 调整状态色
* 导航加上全局用户吊顶导航

**Comment by afc163** [comment]
@bang88 对，从实践上看，数据获取统一交给上层的数据层更合适，远程模式不再推荐使用了。带来不便，非常抱歉。

**Comment by bang88** [comment]
@afc163 还好你列出来了哈

**Comment by afc163** [comment]
是不是就差 menu 了？

**Comment by benjycui** [comment]
rc-menu 已经更新

**Comment by afc163** [comment]
- [ ] #757
- [ ] 内外网站点发布
- [ ] 版本升级发布
- [ ] antd-init 同步发布 https://github.com/ant-design/antd-init/pull/6

**Comment by afc163** [comment]
已发布。
