### ISSUE TITLE
Migrate scripts to Typescript with esm

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#41812]
task list:

- [x] ready #41809
- [x] scripts/argos-upload.js #42070
- [x] scripts/check-commit.js #42068
- [x] scripts/check-cssinjs.js #42072
- [x] scripts/check-demo.js #42062
- [x] scripts/check-site.js #42067
- [x] scripts/check-ts-demo.js #42064
- [x] scripts/check-version-md.js #42059
- [x] scripts/collect-token-statistic.js #42072
- [x] scripts/generate-authors.js #42055
- [x] scripts/generate-cssinjs.js #42072
- [x] scripts/generate-token-meta.js #42077
- [x] scripts/generate-version.js #41809
- [ ] scripts/post-script.js #44742 
- [ ] scripts/print-changelog.js #44744
- [ ] scripts/pre-publish-notice.js
