### ISSUE TITLE
[Theme] V4 Component Token Migration

### ISSUE THREAD

**Issue by MadCcc** [ant-design/ant-design#41884]
### Summary

Migrate component less variables in v4 to Component Token in v5.

[v4 less variables](https://github.com/ant-design/ant-design/blob/4.x-stable/components/style/themes/default.less)

### How to migrate?

In v5, each component has type `ComponentToken` in `style/index.ts`. v4 less variables should be transformed into one of `ComponentToken` and initialized with related Design Token in `genComponentStyleHook`. Then the usage of token in style should also be updated.

Currently many of them has been transformed into `xxxToken` in each component, and we need to put them into `ComponentToken`. If v4 less variable is not in `xxxToken`, we should check if it is suitable for v5.

### Example PR

https://github.com/ant-design/ant-design/pull/42000

1. Migrate Component Token
2. List all less variables in "Migrate less variables to Component Token"

Table may like this:

| Less variables | Component Token | Note |
| --- | --- | --- |
| `@modal-header-padding-vertical` | - | Deprecated for style change |
| `@modal-header-padding-horizontal` | - | Deprecated for style change |
| `@modal-body-padding` | - | Deprecated for style change |
| `@modal-header-bg` | `modalHeaderBg` | - |
| `@modal-header-padding` | - | Deprecated for style change |
| `@modal-header-border-width` | - | Deprecated for style change |
| `@modal-header-border-style` | - | Deprecated for style change |
| `@modal-header-title-line-height` | `modalHeaderTitleLineHeight` | - |
| `@modal-header-title-font-size` | `modalHeaderTitleFontSize` | - |
| `@modal-header-border-color-split` | - | Deprecated for style change |
| `@modal-header-close-size` | - | Deprecated for style change |
| `@modal-content-bg` | `modalContentBg` | - |
| `@modal-heading-color` | `modalHeadingColor` | - |
| `@modal-close-color` | `modalCloseIconColor` | - |
| `@modal-footer-bg` | `modalFooterBg` | - |
| `@modal-footer-border-color-split` | - | Deprecated for style change |
| `@modal-footer-border-style` | - | Deprecated for style change |
| `@modal-footer-padding-vertical` | - | Deprecated for style change |
| `@modal-footer-padding-horizontal` | - | Deprecated for style change |
| `@modal-footer-border-width` | - | Deprecated for style change |
| `@modal-mask-bg` | `colorBgMask` | - |
| `@modal-confirm-body-padding` | - | Deprecated for style change |
| `@modal-confirm-title-font-size` | `modalHeaderTitleFontSize` | - |
| `@modal-border-radius` | `borderRadiusLG` | - |

### Tokens should be migrated

Tokens that should be migrated may meet any of the following conditions：
1. It is still in use in v5, which mean you will find it in `XXXToken`.
2. It is used in v4, and lost in v5. If CSS in v5 is the same as v4, we should add this ComponentToken and initialize it with current v5 token used. If CSS has been changed, we could mark it as deprecated.

### Task list
- [x] Form @poyiding #42774
- [x] TimePicker @poyiding #42607
- [x] Spin @MadCcc #44334
- [x] Input @MadCcc  #44325
- [x] Tree @MadCcc  https://github.com/ant-design/ant-design/pull/44282
- [x] Button @MadCcc #44090
- [x] Checkbox @poyiding #42097
- [x] Descriptions @jrr997  #42038
- [x] Divider @hms181231 #42627
- [x] Dropdown @poyiding #42258
- [x] Empty @hms181231 #42359
- [x] Radio (Radio Buttons) @Yuiai01 #42050
- [x] Layout @MadCcc  #44174
- [x] Mentions @heiyu4585 #42711
- [x] Select @MadCcc #44228
- [x] Cascader @MadCcc #44261
- [x] Anchor @MuxinFeng #42141
- [x] Tooltip @guan404ming #42046
- [x] Popover @heiyu4585 #42337
- [x] Modal @MadCcc  #42000
- [x] Progress @hms181231 #42757
- [x] Menu @MadCcc #43576
- [x] Table @MadCcc #44118
- [x] Tag @heiyu4585 #42053
- [x] Calendar @MuxinFeng #42194
- [x] Carousel @MuxinFeng #42157
- [x] Badge @Wxh16144 #42778
- [x] Rate @MuxinFeng #42135
- [x] Card @heiyu4585 #42061
- [x] Tabs @heiyu4585 #42186
- [x] Avatar @heiyu4585 #42063
- [x] Switch @Yuiai01 #42192
- [x] Pagination @heiyu4585 #42330
- [x] Breadcrumb @heiyu4585 #42342
- [x] Slider @heiyu4585 #42428
- [x] Collapse @Wxh16144 #42938 
- [x] Skeleton @kiner-tang #42134
- [x] Transfer @heiyu4585 #42431
- [x] Message @kiner-tang  #42080
- [x] Alert @any1024 #42142
- [x] List @jrr997 #42041
- [x] Statistic @kiner-tang #42083
- [x] Drawer @kiner-tang #42084
- [x] Timeline @jrr997 #42491
- [x] Typography @jrr997 #42442
- [x] Upload @jrr997 #42042
- [x] Steps @heiyu4585 #42065
- [x] Notification @kiner-tang #42079
- [x] Result @kiner-tang #42081
- [x] Image @guan404ming #42048
- [x] Segmented @kiner-tang#42136

**Comment by MadCcc** [comment]
> Hi @MadCcc, Thanks for the list of V4 Component Token Migration. Do you have an estimate when all Component Tokens will be migrated ?

Yeah, these work would be done in May, and would be published with 5.6.0.

**Comment by MiryksV** [comment]
Thank you for the estimate !

**Comment by kiner-tang** [comment]
mark

**Comment by Wxh16144** [comment]
My pick task:

- [ ] Badge
- [ ] Collapse

**Comment by heiyu4585** [comment]
My pick task:

 Tag
 card

**Comment by any1024** [comment]
My pick task:

Alert

**Comment by yoyo837** [comment]
@heiyu4585 Update the Task list in issue summary is great.

**Comment by kiner-tang** [comment]
Alert,Message

**Comment by hms181231** [comment]
My pick task:

Empty
Divider

**Comment by jrr997** [comment]
My pick task:

Descriptions
List

**Comment by poyiding** [comment]
My pick task:
Button
Checkbox

**Comment by guan404ming** [comment]
My pick task:
Tooltip Image

**Comment by jrr997** [comment]
My pick task:

Timeline
Typography
Upload

**Comment by c0dedance** [comment]
My pick task:
Input

**Comment by MadCcc** [comment]
> My pick task:
> 
> BackTop

BackTop 废弃了就不迁移了

**Comment by yoyo837** [comment]
> My pick task: Button Checkbox

Button 易主了, 换个.

**Comment by MadCcc** [comment]
> > My pick task: Button Checkbox
> 
> Button 易主了, 换个.

私聊过了，我这边会把一些改动比较大的组件 own 掉

**Comment by pengyw97** [comment]
My pick task：

Menu

**Comment by pengyw97** [comment]
My pick task:
Table

**Comment by david-cord** [comment]
Hi there, Thank you for this initiative.  It's currently blocking our migration.

I See `Layout` is checked however you still can't set `layoutHeaderHeight` for example despite it being defined internally.  Can we please expose these and consider this component not complete?

**Comment by MadCcc** [comment]
> Hi there, Thank you for this initiative. It's currently blocking our migration.
> 
> I See `Layout` is checked however you still can't set `layoutHeaderHeight` for example despite it being defined internally. Can we please expose these and consider this component not complete? I believe there are other config values for this component also not exposed (at least on 5.4.7)

I will check it.

**Comment by david-cord** [comment]
> > Hi there, Thank you for this initiative. It's currently blocking our migration.
> > I See `Layout` is checked however you still can't set `layoutHeaderHeight` for example despite it being defined internally. Can we please expose these and consider this component not complete? I believe there are other config values for this component also not exposed (at least on 5.4.7)
> 
> I will check it.

Any news here @MadCcc . I see Layout is still marked as complete when there are many internal tokes unexposed, i.e. layoutHeaderHeight

**Comment by SnowingFox** [comment]
hi, @MadCcc, I see that there are many components that you are responsible for, but they are in a pending state now. May I ask if I need to share some of them? I want to participate in open source.

**Comment by MadCcc** [comment]
> hi, @MadCcc, I see that there are many components that you are responsible for, but they are in a pending state now. May I ask if I need to share some of them? I want to participate in open source.

Thanks for your will to contributing! But it is a delayed work and I'm going to finish it this month.
And sry for everyone watching this issue, my bad to not finish all the work in time.
The rest components need careful migration, so I will do it myself :)

**Comment by yoyo837** [comment]
@david-cord See #44174

**Comment by david-cord** [comment]
> @david-cord See #44174

Cc @daniel-encord

**Comment by MiryksV** [comment]
Thanks @MadCcc and other contributors for finishing the Component Token Migration :pray:

**Comment by dgomez-orangeloops** [comment]
hi all, just to share with you, i'm trying use the Table/ComponentToken, but the interface ComponentToken still empty (v 5.8.4).

it's merged on feature branch, but not in master.

@MadCcc fyi

**Comment by abenhamdine** [comment]
> hi all, just to share with you, i'm trying use the Table/ComponentToken, but the interface ComponentToken still empty (v 5.8.4).
> 
> it's merged on feature branch, but not in master.
> 
> @MadCcc fyi

yes many design tokens are currently only in feature branch, I guess we have to wait for the next weekly release (tomorrow) or perhaps next week.

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/releases/tag/5.9.0 it out.

**Comment by monolithed** [comment]
`padding`, `paddingLG`, `controlPaddingHorizontal`, and `paddingContentHorizontalLG` are not applied to the `Button`component
