### ISSUE TITLE
Refactor Component Style to Adapt CSS Variables

### ISSUE THREAD

**Issue by MadCcc** [ant-design/ant-design#45618]
> Better to read before:
> - https://github.com/ant-design/ant-design/discussions/44654
> - https://github.com/ant-design/ant-design/discussions/45385

## Why need Refactor

Currently we generate different hash and tokens for each theme, which are used in styles to get different styles, and sometimes we will use tokens to calculate a new value. Since we will replace actual value of token with CSS variables like `var(--color-primary)`, tokens could not be used to calculate directly any more. That's the major reason that we must refactor antd component style.

## Refactor Plan

We will put component refactoring tasks in this issue, and these tasks should be all done in November, which means the feature of CSS variables will be released in `5.12.0`. Assigned task that do not have response for more than one week will be called back.

All PRs should be based on `feature` branch. In `feature` branch, all demos are enabled with CSS variables.

The first PR: https://github.com/ant-design/ant-design/pull/45589 . This PR contains feature of CSS variables and refactor of Button. **We will accpect task requestment after this PR is merged**.

### Turn Component Token into CSS variables

1. Create `cssVar.ts` in `components/xxx/style/` directory, and fill in with code below (demonstrated with Button)

```ts
import { genCSSVarRegister } from '../../theme/internal';
import { prepareComponentToken } from '.';

export default genCSSVarRegister('Button', prepareComponentToken);
```

`prepareComponentToken` is the third param of `genComponentStyleHook`. If it exist, we should extract and export it from `style/index.ts`.

This file will export a hook, we will use it in component.

2. Same as `useStyle`, import `useCSSVar` in component:

```diff
import useStyle from './style';
++  import useCSSVar from './style/cssVar';

const Component = () => {
  const prefixCls = 'ant-comp';
  
--  const [wrapSSR, hashId] = useStyle();
++  const [, hashId] = useStyle(prefixCls);
++  const wrapCSSVar = useCSSVar(prefixCls);

--  return wrapSSR(<div />);
++  return wrapCSSVar(<div />);
}
```

`wrapSSR` is useless, we could safely remove it. `useCSSVar` need one param, which should be `rootCls` of the component. In most cases, this `rootCls` could be `prefixCls`. But if `prefixCls` is not always on the root element of component, we could use `useCSSVarCls` to generate a new class and apply it to where `rootClassName` is applied to.

```diff
import useStyle from './style';
++  import useCSSVar from './style/cssVar';
++  import useCSSVarCls from '../config-provider/hooks/useCSSVarCls';

const Component = () => {
  const prefixCls = 'ant-comp';
++  const cssVarCls = useCSSVarCls(prefixCls);
  
--  const [wrapSSR, hashId] = useStyle();
++  const [, hashId] = useStyle(prefixCls);
++  const wrapCSSVar = useCSSVar(cssVarCls);

--  return wrapSSR(<div className={rootClassName} />);
++  return wrapCSSVar(<div className={classNames(cssVarCls, rootClassName)} />);
}
```

In this way, all component token will be transformed into CSS variables. If you customize component token, you could find styles like this:

![image](https://github.com/ant-design/ant-design/assets/27722486/2d220124-f5ad-4ca8-a819-72190d0d1501)

### Refactor Token Calculation

As is said before, we need to refactor token calculation in order to get right value. With CSS variables, all calculation should be transformed with `calc()`, or it should become a component token.

1. Turn Calculation into component token.

In `prepareComponentToken`, tokens remain actual value, which could be directly calculated with js code, so we do not need to refactor this part of code, and can even add more component tokens to avoid transforming. Some calculation for color can not be transformed with `calc()` neither, so we should add component token for them.

```ts
export const prepareComponentToken: GetDefaultToken<'Button'> = (token) => {
  return {
    fontWeight: 400,
    defaultShadow: `0 ${token.controlOutlineWidth}px 0 ${token.controlTmpOutline}`,
    primaryShadow: `0 ${token.controlOutlineWidth}px 0 ${token.controlOutline}`,
    dangerShadow: `0 ${token.controlOutlineWidth}px 0 ${token.colorErrorOutline}`,
  };
};
```

2. Replace Calculation with `token.calc`

Outside of `prepareComponentToken`, we must replace all calculation with `token.calc`. This is a function that will differ by configuration of CSS variables. So we could use one code to get different value with different configuration. For example:

```ts
const genRoundButtonStyle: GenerateStyle<ButtonToken, CSSObject> = (token) => ({
  borderRadius: token.controlHeight,
  paddingInlineStart: token.calc(token.controlHeight).div(2).equal(), // `32 / 2` or `calc(32px / 2)`
  paddingInlineEnd: token.calc(token.controlHeight).div(2).equal(),
});
```

`token.calc` is chainable, and it will do calculation by the order. For more example, take a look at the test cases:

https://github.com/ant-design/ant-design/pull/45589/files#diff-474a355b4973b5cd9ab68c695f77e8fc28504f72f7af6297c8396151bbfff873R13

### Replace `Math.max` and `Math.min` with `token.max` and `token.min`

```diff
-- borderRadius: Math.max(token.borderRadius, 4),
++ borderRadius: token.max(token.borderRadius, 4),
```

Same as `token.calc`, the result with css var will be `min(var(--border-radius), 4px)`

### Replace `px` with `unit()`

For some css properties like `border`, we used to write like this:

```ts
border: `${token.lineWidth}px ${token.lineStyle} ${token.borderColor}`
```

But with CSS varaibles, `` `${token.lineWidth}px` `` will not work. So we should use `unit()` from `@ant-deisng/cssinjs`.

```ts
import { unit } from '@ant-design/cssinjs';

const genStyle = (token) => ({
  border: `${unit(token.lineWidth)} ${token.lineStyle} ${token.borderColor}`
});
```

### Replace `fontSize * lineHeight` with `fontHeight`

We used to write `Math.round(fontSize * lineHeight)` in style to get integer, but `round()` of CSS is not available now. So `fontHeight` is added into token, which is calculated already with `fontSize` and `lineHeight`, and so as `fontHeightSM` and `fontHeightLG`.

## Task List

If you are interested in contributing, please comment in this issue and pick one component that is not assigned to anyone.

Simple PR to reference: https://github.com/ant-design/ant-design/pull/45716
Example with custom `rootCls` and `Math.ceil`: https://github.com/ant-design/ant-design/pull/45727

@MadCcc 
- [x] Button https://github.com/ant-design/ant-design/pull/45589
- [x] DatePicker https://github.com/ant-design/ant-design/pull/45753
- [x] Dropdown https://github.com/ant-design/ant-design/pull/45705
- [x] Input https://github.com/ant-design/ant-design/pull/45782
- [x] InputNumber https://github.com/ant-design/ant-design/pull/45839
- [x] Popover https://github.com/ant-design/ant-design/pull/45705
- [x] Tooltip https://github.com/ant-design/ant-design/pull/45705
- [x] Tour https://github.com/ant-design/ant-design/pull/45705
- [x] Segmented https://github.com/ant-design/ant-design/pull/45716
- [x] Select https://github.com/ant-design/ant-design/pull/45727
- [x] Form https://github.com/ant-design/ant-design/pull/45849
- [x] Slider https://github.com/ant-design/ant-design/pull/45866

@li-jia-nan 
- [x] Affix #45807
- [x] Alert #45825
- [x] Anchor #45808
- [x] App #45806
- [x] Avatar #45824
- [x] Divider #45810
- [x] Flex #45805
- [x] QRCode #45854
- [x] Tag #45823
- [x] Spin #45819 
- [x] Grid #45855
- [x] BackTop #45853
- [x] Table #45856
- [x] Badge #45906
- [x] Breadcrumb #45899
- [x] Descriptions #45900
- [x] Drawer #45905

@RedJue 
- [x] Calendar #45835
- [x] Card #45836
- [x] Carousel #45837
- [x] Cascader #45858
- [x] Checkbox #45859
- [x] Collapse #45862
- [x] ColorPicker #45868

@c0dedance 
- [x] Empty https://github.com/ant-design/ant-design/pull/45802
- [x] Popconfirm https://github.com/ant-design/ant-design/pull/45840
- [x] Skeleton https://github.com/ant-design/ant-design/pull/45842
- [x] Statistic https://github.com/ant-design/ant-design/pull/45841/
- [x] ~~Watermark~~

@kiner-tang 
- [x] Layout #45794
- [x] List #45795
- [x] Mentions #45796
- [x] Menu #45750
- [x] Message #45797
- [x] Modal #45798
- [x] Notification #45799
- [x] Pagination #45800
- [x] Tabs #45803
- [x] Transfer #45804
- [x] Tree #45814
- [x] TreeSelect #45814
- [x] Typography #45818
- [x] Upload #45820

@JarvisArt 
- [x] FloatButton https://github.com/ant-design/ant-design/pull/45861
- [x] Image https://github.com/ant-design/ant-design/pull/45783
- [x] Progress https://github.com/ant-design/ant-design/pull/45821
- [x] Radio #45897
- [x] Rate https://github.com/ant-design/ant-design/pull/45786
- [x] Result https://github.com/ant-design/ant-design/pull/45822
- [x] Space https://github.com/ant-design/ant-design/pull/45869
- [x] Switch https://github.com/ant-design/ant-design/pull/45867
- [x] Timeline https://github.com/ant-design/ant-design/pull/45831

@cc-hearts 
- [x] Steps #45878

**Comment by afc163** [comment]
这是大动作，建议一开始先用一个实验性配置开启。

**Comment by MadCcc** [comment]
> 这是大动作，建议一开始先用一个实验性配置开启。

为了方便重构，在重构分支是默认开启的。整个方案和原先是兼容的，可以配置局部开启

**Comment by RedJue** [comment]
pick:
 Card
 Carousel
 Cascader
 Checkbox
 Collapse
 ColorPicker

**Comment by c0dedance** [comment]
认领 Watermark Statistic Empty Popconfirm skeleton

**Comment by li-jia-nan** [comment]
认领：

Affix
Alert
Anchor
App
Avatar
Divider
Flex
QRCode
Spin
Tag

**Comment by dancerphil** [comment]
想要讨论一个场景，看看在新的 css-variables 模式下怎么支持：

如果两个组件（比如 Button 和 Input 好了）都使用了 `--antd-color-primary`，但是我的设计方案中，希望它们两个是不同的颜色，看起来我需要这样写：

```css
.ant-button {
	--antd-color-primary: red;
}

.ant-input {
	--antd-color-primary: blue;
}
```

然而，我作为一个设计规范的指定者，更希望在一个非常全局的范围定义他们，并且把组件级别的自定义能力交给业务开发者，比如：

```css
/* 设计规范 */
body {
	--antd-button-color-primary: red; /* 当然，此时可以取更好的名字 */
	--antd-input-color-primary: blue;
}

/* 业务层面覆盖 */
.ant-button {
	--antd-button-color-primary: pink;
}
```

这个提案可能可行吗？

**Comment by MadCcc** [comment]
@dancerphil 我们目前希望用户还是使用 ConfigProvider 去修改主题——也就是说是否开启 css 变量对于主题的使用是没有任何影响的。

如果需要在 react 生命周期之外修改 css 变量，自定义主题的 key（用于替代 css-var-hash)，再加上组件的 root class 就可以做到覆盖。

无论如何，我们想尽量淡化用户对 css 变量的认知，有些后续的功能或者拓展仍然可以在此之上进行。

**Comment by kiner-tang** [comment]
我想认领一下：
 Layout
 List
 Mentions
 Menu
 Message
 Modal
 Notification
 Pagination

**Comment by poyiding** [comment]
认领
 Badge
 Breadcrumb
 Descriptions
 Drawer

**Comment by JarvisArt** [comment]
认领
FloatButton
Image
Progress
Radio
Rate
Result
Space
Switch
Timeline

**Comment by MadCcc** [comment]
Task updated for above volunteers.

**Comment by kiner-tang** [comment]
我再认领几个每人认领的吧：
 Tabs
 Transfer
 Tree
 TreeSelect
 Typography
 Upload

**Comment by cc-hearts** [comment]
认领
Steps
