### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4905]
- http://v4-alpha.getbootstrap.com/components/list-group/
- http://www.material-ui.com/#/components/list
- http://semantic-ui.com/elements/list.html
- https://grommet.github.io/docs/list

**Comment by christtrc** [comment]
List组件计划什么时候可用？现有的组件怎么调制一个List？可不可以直接引入Material-UI的List组件？

**Comment by ddcat1115** [comment]
这个预计要到月底发 2.9 才能用，你可以试下 Table[showHeader=false] 能不能满足需求

**Comment by afc163** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/507615/27375459-d5d0f424-56a1-11e7-9eef-71b4c959eda9.png">

**Comment by nikogu** [comment]
内容形态太多了，只能抽离 content（像 card 一样），但是感觉外框不如 card 统一，不太好搞，除非设计上统一内部内容的部分规范，如新 card 那样。

```
<Card
  cover={<img src="xxxx" />}
  actions={[<Icon type="xx" />, <Icon type="xx" />, <Icon type="xx" />]}
+ title="title"
+ avatar={<Avatar src="xxxx" />}
+ description="description"
+ extraContent={<div>xxxx</div>}
/>
```

**Comment by nikogu** [comment]
### 1
![image](https://user-images.githubusercontent.com/1179603/28705006-58b59884-73a0-11e7-93b7-c1ddb23be22f.png)

### 2
![image](https://user-images.githubusercontent.com/1179603/28705012-6004874e-73a0-11e7-8a36-8153554d63fa.png)

### 3
<img width="353" alt="image" src="https://user-images.githubusercontent.com/507615/27375459-d5d0f424-56a1-11e7-9eef-71b4c959eda9.png">

**Comment by nikogu** [comment]
@afc163 @ddcat1115 看看 用法 和 API 是否可行

可配合 Card 使用，变成 Card List。

```jsx
import { List } from 'antd';

ReactDOM.render(
  <div>
    <List
      toolbars={}  // 这两个位置形态固定，所以不抽离成组件，作为配置项
      footer={}
    >
      <List.NewItem type='card | normal' />
      <List.Item>
        <List.Item.logo src='xxx' size={40} radius={40} />
        <List.Item.Meta
          title="Title"     
          description="描述"
        />
        <List.Item.Content>
          Content
        </List.Item.Content>
        <List.Item.Action>
          <a>操作一</a> | <a>操作二</a> 
        </List.Item.Action>
      </List.Item>


      <List.Item 
        vertical // 垂直形态
      >
        <List.Item.logo src='xxx' size={60} radius={5} />
        <List.Item.Meta
          title="Title"     
          description="描述"
          tags=['tag 1', 'tag 2', 'tag 3']
          extra={<Tags />}
        />
        <List.Item.Content>
          Content
        </List.Item.Content>
        <List.Item.Action 
          actions=[{
            icon: '',
            text: '156',
            href: '',
            onClick: () => {},
          }] 
        />
      </List.Item>
    </List>
  </div>
, mountNode);
```

**Comment by afc163** [comment]
- NewItem 直接用 `Button[dashed]`。
- toolbars 是啥？
- vertical => `layout="vertical"`
- Meta 下的 tags、extra 都不要，全部用 description 自定义。
- logo => Avatar：和 Card 保持一致。
- `<List.Item.Action actions={[ ... ]}>` 这种看着蛋疼，我也没想到好的方案。@ddcat1115 和 Card 一并再想想。

**Comment by nikogu** [comment]
> toolbars 是啥？

这货（其实就是 header？感觉 footer 和 header 都没必要，额外写模板好了，然后无限加载那个 button 用一个 `more` 的配置来控制是否显示）：

![image](https://user-images.githubusercontent.com/1179603/29058624-de44ff7a-7c43-11e7-9cfd-63f9c086b4d6.png)

> `<List.Item.Action actions={[ ... ]}>` 这种看着蛋疼，我也没想到好的方案。
```
<List.Item.Action>
    <List.Item.IconText type="start" title="156" onClick={} /> // 这样如何，在 action 里面，默认加 `split`
</List.Item.Action>
```

**Comment by afc163** [comment]
toolbars 不要包括在 List 里。

下面这个是 LoadMore，这个要有。而且，List 组件要集成 infinite load 的功能。

**Comment by ddcat1115** [comment]
不管是横向还是竖向 List，action 位置应该都是固定的（行尾或者尾行），是不是用 prop 比用 child component 好点？

**Comment by ddcat1115** [comment]
而且我觉得实现 List 的时候，不用考虑设计稿中的『网格列表』，也就是长得很像 Card 的那一块，因为这块跟普通认知里面的『列表』不一样，用户肯定不会想到去 List 里找这种效果，列表概念本来也比较宽泛，不可能看到一个一个排列的效果都在 List 里实现。

或者这块可以参考下 http://wiki.jikexueyuan.com/project/bootstrap4/components/card/#section-11

**Comment by afc163** [comment]
对，不用考虑，那个就是 Card 和栅格配合。

**Comment by nikogu** [comment]
@ddcat1115  action 这里，List 的场景有可能会有扩展：

![image](https://user-images.githubusercontent.com/1179603/29061652-526f6838-7c51-11e7-9cba-917af7b09eb6.png)

所以如何抽离成套件的话，再灵活性和规范上面有一个平衡

**Comment by afc163** [comment]
另外也要支持下面的最简用法。

```jsx
<List.Item>
   xxxx
</List.Item>
```

**Comment by nikogu** [comment]
actions 这个，要不支持两种：
1. props，采用设计模板
2. children，方便自定义

```
<List.Item.Action>
    <a>123</a> <Dropdown />
</List.Item.Action>

<List.Item.Action
    actions={}
/>
```

这样的话，虽然 actions props 确实很蛋疼，但是用起来还是方便不少。 @ddcat1115 怎么看

**Comment by ddcat1115** [comment]
<List.Item actions={array<ReactNode>} /> 这样会有什么问题吗？组件做的只是把每一个元素渲染出来，加上分割的竖线，然后渲染位置是固定的

**Comment by afc163** [comment]
不要都支持，选一种。

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design/pull/7150

**Comment by nikogu** [comment]
#### bug
- [ ] loading status should not show the load more button

#### todo

- [ ] test
- [ ] docs (en)
- [ ] support i18n
- [ ] support `infinite  load` & `scroll to load`
- [ ] compatible browser which not support flex box
- [ ] support ListGrid
```jsx
<List grid={{ gutter: 16, column: 4 }}>
  <ListItem><Card /></ListItem>
  <ListItem><Card /></ListItem>
  <ListItem><Card /></ListItem>
  <ListItem><Card /></ListItem>
</List>
```

**Comment by afc163** [comment]
Demo 演示顺序：

- 最基本的，类似：
  <img width="456" alt="image" src="https://user-images.githubusercontent.com/507615/29509365-95a11032-868a-11e7-88d6-6c1b24c1b8ed.png">
- 信息流，复杂一点，增加头像和描述：
  <img width="411" alt="image" src="https://user-images.githubusercontent.com/507615/29509429-d4ade8ae-868a-11e7-902d-71f8353e0709.png">
- 完整全面的。
- 其余功能...

**Comment by afc163** [comment]
@nikogu 目前好像还没实现 scroll infinite load 功能？

**Comment by nikogu** [comment]
@afc163 是的，还没有实现。。。。争取下周实现了

**Comment by afc163** [comment]
- [ ] Use Spin like `Table[loading]`.

**Comment by nikogu** [comment]
同步下进度，今天调研试用了几个三方库，都不是很好用

-  [react-virtualized](https://github.com/bvaughn/react-virtualized)
  - 功能强大，但是使用感觉略复杂了，而且还充斥着 `context`，用法也不太适合我们的场景
- [react-virtual-list](https://github.com/developerdizzle/react-virtual-list)
  - 必须要写死 `height`...而且 grid 貌似不支持

个人倾向自己写一个，用法: https://github.com/ant-design/ant-design/blob/antd-3.0/components/list/demo/infinite-load.md，跟现有无限加载保持一致

自动实现 `virtualized`，无需配置其它额外参数。

#### 思路

全局维护一个 List Item Position，每次 render 新的 List Item，都存 offetTop（这里就需要保证每个 item 有唯一的标识），然后根据 屏幕（或者 container）的 scrollTop，来从对象里面筛选出需要显示的 dom，如果小于 bottom 且可以 load，则自动 load。

那么问题来了：已经存储位置的元素如何更新 offsetTop（交互操作，异步修改）？
完美方案还未相处，不过有些取巧的方法，比如：默认展示 3 屏数据，能够容许一定误差

**Comment by afc163** [comment]
可以参考下 https://github.com/joshwnj/react-visibility-sensor 的实现

**Comment by afc163** [comment]
- [ ] List virtualized 和 Scrolling loaded List 应该交换位置。
- [ ] Scrolling loaded List  这个例子看不太懂，类似 breadcrumb 搞一个 iframe 内部滚动来演示。https://ant.design/components/breadcrumb/#components-breadcrumb-demo-router
- [ ] List virtualized 在 Firefox 下展示有问题。
- [ ] List virtualized 的描述中应该解释下需要 virtualized 的意义（性能？）。

@nikogu

**Comment by nikogu** [comment]
好的，着手改进～

**Comment by afc163** [comment]
- [ ] 头像应该顶部对齐？

![](https://gw.alipayobjects.com/zos/rmsportal/TBRHBXOdRnNvlTsAKzwY.png)

**Comment by afc163** [comment]
- [ ] 没有空数据样式。

`<List dataSource={[]} />`

**Comment by afc163** [comment]
@nikogu

**Comment by andriijas** [comment]
@nikogu
 @afc163   size property is missing in documentation (`<list size="large" />`) - running docs locally. I could fix it and send PR but only for english.

**Comment by andriijas** [comment]
another issue seems to be if i have a list of cards, and i dont use grid prop in list, the last card item will not get 100% width

**Comment by nikogu** [comment]
> another issue seems to be if i have a list of cards, and i dont use grid prop in list, the last card item will not get 100% width

Yes, the width of List children is default to `100%` unless you specify it.

**Comment by andriijas** [comment]
@nikogu 

Actual:

![actual](https://i.imgur.com/1PMslEQ.png)

Expected:

![expected](https://i.imgur.com/fCMqBx4.png)


src:

https://github.com/andriijas/create-react-app-playground/blob/master/src/routes/Users.js

**Comment by nikogu** [comment]
@andriijas https://github.com/andriijas/create-react-app-playground/blob/master/src/routes/Users.js#L60

you need set `itemLayout="vertical"` to List. 

```jsx
...
<List
  itemLayout="vertical"
  dataSource={data}
...
```

**Comment by andriijas** [comment]
thanks. sorry i missed that in the doc. feels a bit strange with horizontal as default but explicit is always better than implicit.
