### ISSUE TITLE
antd@3.0

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5570]
A place to discuss what we want/have to do in `antd@3.0`:

React@16 relative
* [x] React Umbrella support #5377
* [x] Refactor all the `ref: string` to `ref: function`

...

antd's own 
* [x] provide es2015 module format like [this]( https://github.com/reactjs/redux/blob/3b6f3b2b0848b5c6f278cd02cf0d97df75686118/package.json#L7)
* [ ] Remove all deparated features
  1. [ ] and theirs warning
  1. [ ] and then add new warning of upgrade tips
* [x] New Components
  - [x] List https://github.com/ant-design/ant-design/issues/4905
  - [x] Divider https://github.com/ant-design/ant-design/issues/6812
* [x] Default language of `LocaleProvider` should be changed to `en`
* [x] Less aggressive global style: https://github.com/ant-design/ant-design/issues/4331
* [x] Better default typography: https://github.com/ant-design/ant-design/issues/6162
* [ ] ~~Component should work with HOC: https://github.com/ant-design/ant-design/issues/4853~~
* [x] WeekPicker https://github.com/ant-design/ant-design/issues/3825
* [x] Rewrite Steps https://github.com/react-component/steps/pull/39
* [x] Contextmenu dropdown https://github.com/ant-design/ant-design/issues/7232
* [x] external moment while building dist file
   ```jsx
   // We need to link moment before antd's dist file after antd@3.0
   <script src="moment.js"></script>
   <script src="antd.js"></script>
   ```
* [x] Refactor Menu for delay and auto overflow: https://github.com/ant-design/ant-design/issues/2830
* [x] Mention placement: https://github.com/ant-design/ant-design/issues/6663
* [x] TypeScript document: https://github.com/ant-design/ant-design/pull/6193
* [ ] ~~Preact support~~ https://github.com/ant-design/ant-design/issues/5048
...

Tools
* [x] Tools for upgrading antd from 2 to 3 https://github.com/ant-design/ant-design/issues/3759#issuecomment-272353773
* [x] Webpack@2 support cc @sorrycc 
  * [x] Roadhog
  * [x] atool-build
  * [x] dva-cli

...

Ant Design Specification relative
- [x] Bigger default font size, following our designer's plan.

...

Site ant.design
- [ ] ~~Rewrite demo in TypeScript #5390~~
- [x] Let demo code editable or a Playground #5140 

...

**Comment by afc163** [comment]
#5377

**Comment by bang88** [comment]
- [ ] Rewrite demo in TypeScript #5390 
- [ ] Let demo code editable or a Playground ?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5140 can be a editable playground.

**Comment by afc163** [comment]
- [ ] Maybe a bigger default font size

**Comment by yesmeck** [comment]
Refactor `cloneElement` to `context`?

**Comment by ddcat1115** [comment]
- [ ] reopen #1473 ?

**Comment by plandem** [comment]
I still hope for more robust built-in i18n support:
https://github.com/ant-design/ant-design/issues/5554

**Comment by infeng** [comment]
Improve and perfect Component ts definition`s comment?

**Comment by hbrls** [comment]
What about tools of 2->3, or even 1->3?

**Comment by benjycui** [comment]
@yesmeck this https://github.com/ant-design/ant-design/issues/5570#issuecomment-290622803 means that we need to give up `Tabs.TabPane[key]` and `Menu.Item[key]`...

> I still hope for more robust built-in i18n support #5554 (comment)

@plandem I am evaluating, let's keep discussing in that issue.

> Improve and perfect Component ts definition`s comment?

@infeng this is why I want to re-write demo in TypeScript, so that we can notice issues in definition https://github.com/ant-design/ant-design/issues/5390

> What about tools of 2->3, or even 1->3?

Yep, we still need to provide tools like https://github.com/ant-design/ant-design/issues/3759#issuecomment-272353773 , though it is not a perfect solution

**Comment by benjycui** [comment]
@sorrycc what do you think about `webpack@2`?

**Comment by xueqingxiao** [comment]
Any progress about rich text editor? #1083

**Comment by afc163** [comment]
https://github.com/MicheleBertoli/css-in-js

**Comment by afc163** [comment]
Editor may not in our recently plan for now.

**Comment by benjycui** [comment]
ThemeProvider should be discussed in https://github.com/ant-design/ant-design/issues/5656

But I am not sure if we have time to introduce it into `antd@3.0`.

**Comment by thomaslwq** [comment]
Add new feature for Chart
Such as Pie,hisgram etc.

**Comment by plandem** [comment]
> Add new feature for Chart
I'm against it. It's a different class of components. 

If you want charts from same team, you can try this one:
https://antv.alipay.com/g2/doc/index.html

**Comment by JesperWe** [comment]
The one component missing from antd that I find myself implementing again and again in all projects is an off-screen sidebar. 

[react-sidebar](https://github.com/balloob/react-sidebar) is a nice component, but it breaks everything having to do with scrolling on the page, so it is pretty useless. An integrated sidebar, preferrably with swipe support on touch devices would be my biggest wish for 3.0!

**Comment by benjycui** [comment]
@JesperWe I think what you need is [Layout.Sider](https://ant.design/components/layout/#components-layout-demo-responsive)

**Comment by JesperWe** [comment]
@benjycui Actually I haven't looked at the Sider for a few months, I see it has a custom trigger since 2.6, which makes it more useful than before. However it still squeezes the content column to become narrow when it appears, so it is not usable as a sidebar. 

But it could be extended to work like a sidebar with some new props:

- `cover: true` to make it appear on top of the page content instead of squeezing it.
- `mask: true` to show a mask over the not-covered part of the page when Sider is on top.
- `maskCloseable: true` to make it collapse when clicked outside.

and finally in a dream world

- `swipeable: true` to better support touch devices (but since you are probably thinking of antd as a desktop thing, this could be achieved outside of antd too).

**Comment by gudh** [comment]
@benjycui @JesperWe In the [Layout.Sider](https://ant.design/components/layout/#components-layout-demo-responsive) demo, the content get squeezed (which is bad) when Sider opens in mobile.

Is it possible to push the content to the right like Sider as well?

**Comment by benjycui** [comment]
Yet another breaking change I want to do in next major version, and want you to provide advice: https://github.com/ant-design/ant-design/issues/6139

**Comment by benjycui** [comment]
@JesperWe so, what you need is some thing like [Drawer](https://mobile.ant.design/components/drawer).

And we should not discuss details of features here, just open a new issue to discuss.

**Comment by JesperWe** [comment]
@benjycui Ok so I rephrase my 3.0 dream :-) : Something like [Drawer](https://mobile.ant.design/components/drawer) integrated into antd (Because adding antd-mobile/Drawer makes the bundle much bigger and adds lots of unwanted react-native stuff)

**Comment by plandem** [comment]
Compare results and consider **rollup** as library packer.

Here is some thoughts:
https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by benjycui** [comment]
> Compare results and consider rollup as library packer.

We can do this in 2.x, for developers will not feel any changes.

And you can open a new issue to discuss this idea @plandem

**Comment by afc163** [comment]
Try https://github.com/styled-components/styled-components

**Comment by paranoidjk** [comment]
About styled-components, i have too problems:

- the autoprefixer library may not very reliable compare to postcss https://github.com/styled-components/styled-components/blob/master/src/utils/autoprefix.js#L6.  Or we can say,   once pick css-in-js, we will lose convenience of post-css plugin system, such as px-to-rem?
- we have to remain whole current css classname for compatibility,  while styled-components will generated it's own classname for style, it will be redundancy and hard to maintain?

**Comment by afc163** [comment]
That is why `try` existed.

**Comment by benjycui** [comment]
> we have to remain whole current css classname for compatibility, while styled-components will generated it's own classname for style, it will be redundancy and hard to maintain?

Actually, this is not an issue. Current CSS classnames are not just for compatibility, but selectors which we can use in test(e.g. enzyme). So, we must keep them.

**Comment by philpl** [comment]
@paranoidjk @afc163 Hiya, I'm one of the styled-components core-contributors and found this thread due to an opened issue on our repo (see above), that informed me that this lib doesn't support SC. By chance I then found this conversation :wink: – Ok, context aside now

> the autoprefixer library may not very reliable compare to postcss

We've carefully chosen `stylis` and are closely working together with @thysultan, who develops it. We wouldn't have chosen it, if it wasn't a worthy replacement of PostCSS and the few issues that it had (a couple of missing prefixes in v3), were resolved very quickly. The v2 itself has been in the making for a few months btw, and is now finally out. We can definitely vouch on that part. Let this implementation detail be our worry, if you'd go with SC :smile:

The file you're pointing to is not in use and was deleted now btw, and is part of the old auto-prefixing with inline-style-prefixer. But even that is (and was for us) a very, very, *very* trusted solution through out the css-in-js community by @rofrischmann.

> Or we can say, once pick css-in-js, we will lose convenience of post-css plugin system, such as px-to-rem?

Since in interpolations in our tagged template literals you can just use any JS, simple functions can replace all that stuff. We actually have a separate project called "polished" that is like the lodash for CSS-in-JS and comes with all mixins (i.e. helper functions) that you'd expect from SASS/LESS and the likes: https://polished.js.org

(We indeed neither use PostCSS anymore as mentioned above, nor have we supported its plugins btw)

> we have to remain whole current css classname for compatibility, while styled-components will generated it's own classname for style, it will be redundancy and hard to maintain?

If you need to attach custom classnames, you can easily use our `.attrs` method, which allows you to attach additional props to a component. For example:

```js
const ButtonLink = styled.a.attrs({
  className: 'your-custom-extra-classname'
})`
   ... // css and stuff
`
```

Some more goodies and features:

- You write just CSS (as you might already know), and the only additions are ampersands and nestedness
- There's no styles+component mapping
- Everything's a component
- You can write mixins/shared styles with our `css` helper

I'm here if you need more help. If you need some more info though, check out our new website :100: https://styled-components.com

**Comment by eddhannay** [comment]
@philpl @benjycui

> Current CSS classnames are not just for compatibility, but selectors which we can use in test(e.g. enzyme). So, we must keep them.

Most of the class selectors in the tests look like they could be replaced with [display name](https://github.com/airbnb/enzyme/blob/master/docs/api/selector.md#3-a-react-components-displayname) selectors instead. This isn't true for all tests, but it would get us most of the way there. I wouldn't mind taking this on.

One place styled-components could help is in [customising the theme](https://ant.design/docs/react/customize-theme). It seems like it would give us more flexibility than the first approach and better optimisation than the second approach.

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by ffxsam** [comment]
I second @philpl - PLEASE make styling a lot easier in Ant Design. Currently it's a real pain. `styled-components` is amazing.

**Comment by benjycui** [comment]
I think we can solve this issue at the same time https://github.com/ant-design/ant-design/issues/4998 , if we refactor to `styled-component`.

**Comment by benjycui** [comment]
Updated:

![image](https://user-images.githubusercontent.com/3580607/27720085-ee9d3974-5d89-11e7-8716-1ea747df5376.png)

**Comment by ffxsam** [comment]
This is how I'm currently styling Ant Design in a React project. It's not the greatest, because we have to go through the _entire_ Ant Design library and style everything.

```js
// @flow

import { injectGlobal } from 'styled-components';
import Color from 'color';

/*
 * We'll start with just one theme for now. Define colors and other styles here.
 * More themes can be easily added later. Look in ./App.js to see where this
 * theme is actually used.
 */

const mainTheme = {
  primaryColor: Color('#fd3d57'),
  primaryTextColor: Color('#fff'),
};

const defaultTheme = mainTheme;

// Inject global styles - seems to be the only way to customize Ant Design
// PLEASE ADD STYLES IN ALPHABETICAL ORDER for everyone's sanity. Thanks.
injectGlobal`
  .ant-btn {
    &:hover {
      border-color: ${defaultTheme.primaryColor
        .lighten(0.2)
        .toString()} !important;
      color: ${defaultTheme.primaryColor.lighten(0.2).toString()} !important;
    }

    &:active {
      border-color: ${defaultTheme.primaryColor
        .darken(0.2)
        .toString()} !important;
      color: ${defaultTheme.primaryColor.darken(0.2).toString()} !important;
    }
  }

  .ant-btn-primary {
    background-color: ${defaultTheme.primaryColor.toString()} !important;
    border-color: ${defaultTheme.primaryColor.toString()} !important;
    color: ${defaultTheme.primaryTextColor.toString()} !important;

    &:hover {
      background-color: ${defaultTheme.primaryColor
        .lighten(0.2)
        .toString()} !important;
      border-color: ${defaultTheme.primaryColor
        .lighten(0.2)
        .toString()} !important;
      color: ${defaultTheme.primaryTextColor.toString()} !important;
    }

    &:active {
      background-color: ${defaultTheme.primaryColor
        .darken(0.2)
        .toString()} !important;
      border-color: ${defaultTheme.primaryColor
        .darken(0.2)
        .toString()} !important;
      color: ${defaultTheme.primaryTextColor.toString()} !important;
    }
  }

  .ant-btn-clicked:after {
    border: 0 solid ${defaultTheme.primaryColor.toString()} !important;
  }

  .ant-switch-checked {
    background-color: ${defaultTheme.primaryColor.toString()} !important;
    border-color: ${defaultTheme.primaryColor.toString()} !important;
  }
`;

export default defaultTheme;
```

**Comment by bkniffler** [comment]
I'd just like to throw [fela](https://github.com/rofrischmann/fela) in as an alternative to styled-components. Its more [modular](http://fela.js.org/docs/introduction/Ecosystem.html#plugins) and faster. Also, cloudflare decided to build there ui with it instead of styled-components.

Whatever you guys decide, I'd be really happy to see antd use some css-in-js solution instead of less.

**Comment by tz5514** [comment]
`styled-components` is better choice for building modern, modular, scalable UI components.
most important, it can make component render independently that without any external css file.
that make partial importing component with minimal required styles be possible.
hope antd@3.0 will use it.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/tree/antd-3.0

@benjycui @yesmeck @ddcat1115

**Comment by benjycui** [comment]
cc @nikogu

**Comment by ddcat1115** [comment]
add #4853 ?

**Comment by benjycui** [comment]
> add #4853 ?

It's difficult, for some components use `key` as part of API, we cannot fix this until we rename all the API's names. e.g.

```jsx
key => id
expandedKeys => expandedIds
selectedKeys => selectedIds
....
```

It will be a breaking change, but such kind of breaking change can be resolve by [antd-codemod](https://github.com/ant-design/antd-codemod).

We can keep discussing in #4853

**Comment by lhz516** [comment]
>  Rewrite demo in TypeScript

Will demo be Typescript only or both JS and Typescript? I hope to keep both.

**Comment by yesmeck** [comment]
https://github.com/react-bootstrap/react-overlays/issues/188

Make sure `Modal` works with react 16.

**Comment by codepunkt** [comment]
Is `styled-components` or a css-in-js solution of the maintainers/collaborators choice still an option?
I would love that and would like to help with refactoring :)

**Comment by yesmeck** [comment]
It's too many works to migrate our less files to styled-components, I'm afraid we won't introduce styled-components in antd 3. But, since styled-components can apply styles to antd's component without intruding antd's code, so if someone interest in using styled-components with antd, here is a example https://github.com/yesmeck/styled-antd

**Comment by cloudmu** [comment]
@codepunkt @yesmeck would love to see examples of antd with [glamorous](https://github.com/paypal/glamorous)

**Comment by dalerka** [comment]
@yesmeck  @afc163  how about going JSS for CSS-in-JS?   
Do you think the [advantages listed here](https://material-ui-next.com/customization/css-in-js/) could make it more feasible than *styled components*?

**Comment by abenhamdine** [comment]
Perhaps it's more related to tooling ecosystem, but it could be a good idea to ensure that antd 3.0 works with babel 7.
Especially with babel typescript built-in generation planned in 7.0.
It could greatly simplify use of antd/typescript with create-react-app

**Comment by andriijas** [comment]
How about investigating using css next instead of less?

http://cssnext.io/features/

**Comment by andriijas** [comment]
Consider dropping support for IE6-8, maybe even all versions below IE11.

It will make the css file slimmer and faster to download. React doesnt even support IE below version 9 so .clearfix, -ms-filter etc can be safely removed.

**Comment by megawac** [comment]
ant already only officially supports IE9+

**Comment by andriijas** [comment]
Ok. Check antd.css (https://cdnjs.cloudflare.com/ajax/libs/antd/2.13.6/antd.css)  contains some IE6-8 hacks that should be removed then.  

Example:
```
  /* IE6-IE8 */
  -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(sizingMethod='auto expand', M11=1, M12=0, M21=0, M22=1)";
  zoom: 1;
```
```
.clearfix {
  zoom: 1;
}
```

**Comment by benjycui** [comment]
@andriijas I think it had been removed in `antd-3.0`, if you still see any hack, just PR to remove it, thanks.

**Comment by malekjaroslav** [comment]
I have a big issue with styled-components and antd form. When I wrap components that are decorated with fieldDecorator to a wrapper that is styled with styled-components the field stops working. I don't really understand this issue but I have to wrap it to <div> with inline styles to make it work. This is really anoying...

**Comment by luckyYao** [comment]
Week Selector!!!

**Comment by philpl** [comment]
@malekjaroslav that might be related to incorrect usage. Can you open an issue on the styled-components repo, so I can help you?

**Comment by andriijas** [comment]
@benjycui What do you think of responsive helper in antd3.0?  Something like this https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss  in react

```
import { Utils } from "antd";
const { Display } = Utils;

const Foo = props => (
  <h1>
    My idiotic example header
    <Display xs="block" sm="inline" print="inline-block">my subheader is fantastic</Display>
  </h1>
);

const Zoo = props => (
  <h1>
    My idiotic example header
    <Display xs={{display: "block", className: ..}} sm="inline" print="hidden">my subheader is fantastic</Display>
  </h1>
);

```

I can make PR for initial if you need help but will need help with translating documentation etc.

**Comment by benjycui** [comment]
@andriijas just use https://github.com/contra/react-responsive . We just add UI component which follow Ant Design Specification to antd. Anyway, thanks 😄

**Comment by andriijas** [comment]
Yes, i saw it in ant-design-pro repository. I will make wrapper with breakpoints from antd.

**Comment by FoxxMD** [comment]
Looking forward to this release!

**Comment by yesmeck** [comment]
Hello everyone, I've just released antd@3.0.0-rc.1, See https://github.com/ant-design/ant-design/issues/8233

**Comment by mvelker** [comment]
很期待新版本的发布，因为出来了才能开始用antd pro的组件。你们还打算月底出炉吗?

多谢你们提供了这么好的前端组件，你们已经超越谷歌的material

Really excited for this release as it is the blocker for starting to use the new antd pro components. Is expected release timeframe still end of November?

Thanks for providing such an awesome library. You guys are leaving Google's Material UI is the dust.

**Comment by afc163** [comment]
https://medium.com/ant-design/announcing-ant-design-3-0-70e3e65eca0c

Ant Design 3.0 released now! 🎉 🎉 🎉

**Comment by Enalmada** [comment]
+1 for styled-components/emotion/fela support in a future release.
