### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#978]
Change any time, keey your attention!

- [x] compatible with React@0.15.0 #1340
- [x] Layout improvement: Responsive and gutter #1082
- [x] Website via react and router #1093 #1259
- [x] Card component #1044 #855 
- [x] Style orgnazition #900
- [x] Rate component [sketch picture](https://os.alipayobjects.com/rmsportal/lvzpFjnxtZxQwOg.png)
- [x] Better locale support #1117
- [x] Remove Validation #1096
- [x] Table: scroll columns replace paging columns https://github.com/react-component/table/issues/23
- [x] Table: controlled filters and sorter #971
- [x] Affix bottom #1094
- [x] Deprecate QueueAnim
- [x] Improve Progress API #1214 
- [x] icon Button #1199
- [x] correct warn name #1225 
- [x] Error Step #1098
- [x] Fixed Background Modal #1195
- [x] Precise Popup Animation #1339
- [x] Improve Select selected style again... #1364
- [x] Indepent antd dist files #1338
- [x] Focused style of Form Components #1358 

Changelog for now: https://github.com/ant-design/ant-design/issues/1050

**Comment by Carrotzpc** [comment]
1.0 不打算支持服务端渲染吗？[#215](https://github.com/ant-design/ant-design/issues/215)

**Comment by plandem** [comment]
think about 'redux' for webiste :) E.g. for routing you can use nice:
https://github.com/callum/redux-routing

**Comment by afc163** [comment]
Deprecate QueueAnim.

**Comment by plandem** [comment]
why do you want to deprecate 'QueueAnim'?

**Comment by afc163** [comment]
It will be moved to http://motion.ant.design/#/component/queue-anim where contains other animation components.

And it doesn't have any style in `antd`, so you can still use it via `import Queue from 'rc-queue-anim'` easily.

**Comment by plandem** [comment]
cool, didn't heard about ant-motion before :) thanks for link ) You guys rocks!

**Comment by afc163** [comment]
It is new and unfinished yet. :santa:

**Comment by afc163** [comment]
同步下 ant-tool 的升级：https://github.com/ant-tool/ant-tool.github.io/issues/4
